### ISSUE TITLE
Property is not expected here after Bundle command with dereference

### ISSUE THREAD

**Issue by jeremyfiel** [Redocly/redocly-cli#1001]
**Describe the bug**
I have a response schema defined with an external JSON Schema Draft-04 and the `examples` defined with a `$ref` to an external file as well.  Because Redocly doesn't support example validation #919, there is no error thrown when I initially design the file. 

After running `bundle` command with `-d` flag.  My examples are giving an error of `property...not expected here` 

It appears to have a valid `example` map entry and the schema matches the `response schema`

![image](https://user-images.githubusercontent.com/32110157/214651519-41b5037f-10c6-4ab0-8236-608fd8c7cdfe.png)

![image](https://user-images.githubusercontent.com/32110157/214651334-f679c63f-8065-4f6c-a803-0e897b6d7310.png)

**Comment by RomanHotsiy** [comment]
Hey @jeremyfiel, could you share a minimal reproducible example? Thanks.

**Comment by adamaltman** [comment]
I think the examples map is incorrect though (from the screenshot). 
```
examples:
  response:
    workerAwardsHistory: ...
```

The examples map has a key "response" in your case, but the value should be an example object which has a `summary`, `description`, `value` (or `externalValue`). For example:

```
examples:
  response:
    value:
       workerAwardsHistory: ...
```

Or possibly:

```
examples:
  response:
    externalValue: ./schemas/etc...json
```

**Comment by jeremyfiel** [comment]
thanks @adamaltman   i think that was it. 

and because Redocly doesn't parse externalValue, it returns the example object.  is that the correct behavior? with #919, i would expect the `externalValue` to be parsed and return the full schema. 🤞 

![image](https://user-images.githubusercontent.com/32110157/214969697-b9373c39-85a0-44ac-a5e7-dd9a9bf01733.png)

**Comment by RomanHotsiy** [comment]
@jeremyfiel yes, I believe we don't parse externalValue at the moment.

**Comment by tatomyr** [comment]
Hi @jeremyfiel,
Do you think we can close this issue?
