### ISSUE TITLE
Issue with validating parameters

### ISSUE THREAD

**Issue by Orest-Yastremskyy** [Redocly/redocly-cli#1009]
**Describe the bug**

>We're seeing an issue where the [redocly validator](https://www.npmjs.com/package/@redocly/cli) isn't validating like it should be. The example I'm using is for a path parameter (see attachment for full doc):
```
"parameters": [
          {
            "name": "id",
            "in": "query",
             "$ref": "#/components/schemas/BasePlace"
          }
        ]
```
>I believe the above should be invalid, but redocly validator says it's valid. All other validators I've used would error on this. I believe the correct structure is:
```
"schema": {
     "$ref": "#/components/schemas/BasePlace"
 }
```

Openapi spec to reproduce:

[openapi.json.zip](https://github.com/Redocly/redocly-cli/files/10557129/openapi-dat.json.zip)

**Additional information**

>Additional info:
Using your old CLI tool:
npx @redocly/openapi-cli lint fooApi.json
does give some errors. See attached for those errors and an updated example spec.
[Archive 2.zip](https://github.com/Redocly/redocly-cli/files/10557142/Archive.2.zip)

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_75kng)

**Comment by tatomyr** [comment]
Are they using `extend: recommended` explicitly? Please see the [docs](https://redocly.com/docs/cli/configuration/#extends-list).

**Comment by tatomyr** [comment]
Looks like `extends: recommended` has not been explicitly set. Please see the docs: https://redocly.com/docs/cli/configuration/#extends-list.
