### ISSUE TITLE
`redocly lint` does not catch invalid parameter syntax

### ISSUE THREAD

**Issue by unional** [Redocly/redocly-cli#1019]
```ts
paths:
  /abc/<id>:
    get:
      parameters:
        - name: id
           in: path
```

Lint doesn't detect above as an error that it should be `{id}` instead of `<id>`

**Expected behavior**
`redocly lint` should fail and detect the above error correctly.

**Comment by tatomyr** [comment]
Hi @unional,

Could you provide your setup? E. g. Redocly CLI and node versions? What ruleset do you use (does it include [this rule](https://redocly.com/docs/cli/rules/path-parameters-defined/#path-parameters-defined))? Could it be that the indentation is wrong (I see one more space before ` in: path`)?

**Comment by lornajane** [comment]
@unional do you have any more information for us on this? I tried with a simple OpenAPI description and the rule `path-parameters-defined` picks up this problem correctly when the parameter is described for an endpoint but not present in the path. Please let us know if you can share anything more than might help us understand.

**Comment by unional** [comment]
thx. Yes, when `path-parameters-defined` turned on, it correctly detects it.

Should that be turned on by default?

**Comment by tatomyr** [comment]
@unional if you don't use any config file, lint will automatically use the default `recommended` ruleset which includes this rule. However, if you have `redocly.yaml` defined, you have either to specify `extends: [recommended]` explicitly ([see the docs](https://redocly.com/docs/cli/rules/#recommended-config)) or define the rule itself.

**Comment by unional** [comment]
I see. thx. Didn't see that in the doc.
