### ISSUE TITLE
Support OAS3.1 for joining

### ISSUE THREAD

**Issue by mibejjh** [Redocly/redocly-cli#1021]
**Is your feature request related to a problem? Please describe.**

Currently, all features except "join" support OAS3.1.
I am considering changing the openapi version from OAS3.0 to OAS3.1, but join is causing the following error.

```
Only OpenAPI 3 is supported: /home/mibe/git/rcp/sbc-api-doc/openapi/v1/favorite_robots.yaml 
```

**Describe the solution you'd like**

When I run join, it only checks for OAS3.0, but please include OAS3.1 as well.

https://github.com/Redocly/redocly-cli/blob/28e7e8308fd0ba6380cf2a2b3a4b5f10115322f3/packages/cli/src/commands/join.ts#L122-L126

**Comment by bcoughlan** [comment]
For what it's worth I took out the version check that @mibejjh mentioned and my OAS 3.1 specs joined just fine.

**Comment by tatomyr** [comment]
### Adding a testing set for further development.


### The API descriptions that have webhooks in them:

https://github.com/APIs-guru/openapi-directory/blob/main/APIs/listennotes.com/2.0/openapi.yaml
https://github.com/APIs-guru/openapi-directory/blob/main/APIs/codat.io/assess/1.0/openapi.yaml
https://github.com/APIs-guru/openapi-directory/blob/main/APIs/adyen.com/BalancePlatformReportNotification-v1/1/openapi.yaml
https://github.com/APIs-guru/openapi-directory/blob/main/APIs/adyen.com/BalancePlatformConfigurationNotification-v1/1/openapi.yaml
https://github.com/APIs-guru/openapi-directory/blob/main/APIs/adyen.com/BalancePlatformPaymentNotification-v1/1/openapi.yaml
https://github.com/APIs-guru/openapi-directory/blob/main/APIs/adyen.com/BalancePlatformTransferNotification-v3/3/openapi.yaml
https://github.com/APIs-guru/openapi-directory/blob/main/APIs/adyen.com/ManagementNotificationService-v1/1/openapi.yaml
https://github.com/APIs-guru/openapi-directory/blob/main/APIs/adyen.com/MarketPayNotificationService/3/openapi.yaml
https://github.com/APIs-guru/openapi-directory/blob/main/APIs/adyen.com/MarketPayNotificationService/4/openapi.yaml
https://github.com/APIs-guru/openapi-directory/blob/main/APIs/adyen.com/MarketPayNotificationService/6/openapi.yaml
https://github.com/APIs-guru/openapi-directory/blob/main/APIs/adyen.com/MarketPayNotificationService/5/openapi.yaml
https://github.com/APIs-guru/openapi-directory/blob/main/

### Also a set that use x-webhooks in case that's useful:
https://github.com/APIs-guru/openapi-directory/blob/main/APIs/svix.com/1.4/openapi.yaml
https://github.com/APIs-guru/openapi-directory/blob/main/APIs/rebilly.com/2.1/openapi.yaml
https://github.com/APIs-guru/openapi-directory/blob/main/APIs/github.com/api.github.com/1.1.4/openapi.yaml
https://github.com/APIs-guru/openapi-directory/blob/main/APIs/github.com/api.github.com.2022-11-28/1.1.4/openapi.yaml
https://github.com/APIs-guru/openapi-directory/blob/main/APIs/github.com/ghes-3.8/1.1.4/openapi.yaml
https://github.com/APIs-guru/openapi-directory/blob/main/APIs/github.com/ghec/1.1.4/openapi.yaml
https://github.com/APIs-guru/openapi-directory/blob/main/APIs/github.com/github.ae/1.1.4/openapi.yaml
https://github.com/APIs-guru/openapi-directory/blob/main/APIs/github.com/ghec.2022-11-28/1.1.4/openapi.yaml
https://github.com/APIs-guru/openapi-directory/blob/main/APIs/github.com/ghes-3.7/1.1.4/openapi.yaml
https://github.com/APIs-guru/openapi-directory/blob/main/APIs/velopayments.com/2.35.57/openapi.yaml
https://github.com/APIs-guru/openapi-directory/blob/main/APIs/nexmo.com/number-insight/1.2.1/openapi.yaml
https://github.com/APIs-guru/openapi-directory/blob/main/APIs/nexmo.com/sms/1.2.0/openapi.yaml
https://github.com/APIs-guru/openapi-directory/blob/main/APIs/nexmo.com/messages-olympus/1.4.0/openapi.yaml
https://github.com/APIs-guru/openapi-directory/blob/main/APIs/apideck.com/vault/9.5.0/openapi.yaml
https://github.com/APIs-guru/openapi-directory/blob/main/APIs/apideck.com/issue-tracking/9.5.0/openapi.yaml
https://github.com/APIs-guru/openapi-directory/blob/main/APIs/apideck.com/ats/9.5.0/openapi.yaml
https://github.com/APIs-guru/openapi-directory/blob/main/APIs/apideck.com/lead/9.5.0/openapi.yaml
https://github.com/APIs-guru/openapi-directory/blob/main/APIs/apideck.com/pos/9.5.0/openapi.yaml
https://github.com/APIs-guru/openapi-directory/blob/main/APIs/apideck.com/crm/9.5.0/openapi.yaml
https://github.com/APIs-guru/openapi-directory/blob/main/APIs/apideck.com/file-storage/9.5.0/openapi.yaml
https://github.com/APIs-guru/openapi-directory/blob/main/APIs/apideck.com/accounting/9.5.0/openapi.yaml
https://github.com/APIs-guru/openapi-directory/blob/main/APIs/apideck.com/hris/9.5.0/openapi.yaml
