### ISSUE TITLE
Push command doesn't recognize API definitions with a space after upgrading to '1.0.0-beta.121'

### ISSUE THREAD

**Issue by ZyzychO** [Redocly/redocly-cli#1031]
**Describe the bug**
After upgrading the CLI version to 1.0.0-beta.121, Redocly CLI doesn't recognize the API definitions with a space, it shows the error message `Destination argument value is not valid, please use the right format: <@organization-id/api-name@api-version>`
<img width="789" alt="Screenshot 2023-03-23 at 19 00 46" src="https://user-images.githubusercontent.com/106024790/227279489-fae6ebff-0180-40f5-aad5-3a810a28eb30.png">

**To Reproduce**
1. Go to API Registry
2. Tap on the button "ADD API" and select source "Upload from CI/CD"
3. Name the API registry 'test redocly'
4. Create a redocly.yaml file in the local environment along with the API definition. 
5. Add the 'organization' and 'apis' properties into the redocly.yaml file.
The information should be taken from here: 
<img width="986" alt="Screenshot 2023-04-03 at 18 42 42" src="https://user-images.githubusercontent.com/106024790/229560212-de295164-fdd6-468d-b48d-2d8588e7aa01.png">

<img width="1145" alt="Screenshot 2023-04-03 at 18 40 24" src="https://user-images.githubusercontent.com/106024790/229559569-c1e3418e-7311-4063-a901-0b0a7070f093.png">

6. Push the API definition into the API Registry with the command: npx @redocly/cli@latest push [openapi.json]

**Expected behavior**

API definition should be pushed into the API Registry.

**Redocly Version(s)**
'1.0.0-beta.121' and later 

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_9k0b0)

**Comment by AntonKozachuk** [comment]
@ZyzychO I create this and the command worked well:
<img width="698" alt="image" src="https://user-images.githubusercontent.com/54616703/227920982-e98cf7ae-a1d8-4602-84a3-62f394564246.png">

**Comment by ZyzychO** [comment]
Hello, I'm sorry it's  my bad. 

In order to reproduce this issue, you have to place the information about org id and API name in redocly.yaml file. 

Let me edit the bug description.
