### ISSUE TITLE
Make `push` command clearer in usage and help text

### ISSUE THREAD

**Issue by lornajane** [Redocly/redocly-cli#1032]
**Is your feature request related to a problem? Please describe.**

The existing `push` command is a bit confusing with arguments named `maybeX` and some positionals that are optional.

**Describe the solution you'd like**

I'd like a more precise and friendly command. As a logged in user I should be able to do:

```
redocly push awesome-api.yaml --organization AwesomeCorp --name AwesomeApi --version v1.3
```

The API (API name or file/path to API description) is optional in the first parameter position, and we have this pattern across the other commands too, so I think it's a convention to keep.

The current command uses a "destination", which should be a named parameter rather than positional (since both positionals are optional). We don't use destination anywhere else that I can find, and it's a composite where the docs show the user how to find the API name, and the version, and add the correct punctuation (optionally with the organization as well). I think it's simpler just to ask for the things we actually want and that they know - the API name and desired version.

With no arguments at all, all APIs configured will be pushed to their existing destinations: `redocly push`

The current branch name is already supported as a parameter `--branch` but this has no help text to explain it, we should add that. IT would be used like this: `redocly push myAwesomeAPI --branch cool-feature-7`

The example above uses the organization ID from the configuration file, the API root, name and version as set in the configuration file.

To push a new version of an existing API:  `redocly push myAwesomeAPI --version v1.44`

**Describe alternatives you've considered**

Keeping the current setup is an option, but #265 and #1031 indicate that the destination piece is difficult to get right - with separate arguments we can be more specific about what is wrong when a user makes a mistake, and potentially allow people to quote the strings on the command line to accommodate spaces/symbols, which is why I think this suggestion might be easier to use.

**Additional context**

It's a breaking change - which is OK in beta but let's work hard at writing really good changelogs and error messages (I'm happy to help with this), to help users understand what should be different. We could also consider releasing one version that silently supports the old syntax, to give people a chance to move over, and drop it in a later release.

**Remaining questions**

What happens if the version isn't specified? Does the tool push to a new version, or the last known one?

How does the `upsert` parameter fit in with this? The `upsert` parameter currently has no help text (and the docs assume I know what an upsert is in this context) - so let's fix that! If I push to an existing API version without setting the `upsert`, would the push fail?

If users need to know their Organization, API name and versions, could we make those available from command line as a quick lookup/listing? I don't think we know how many people have this already in a configuration file.

Are preprocessors applied at this step? Decorators? Linting? Bundling? We have the `--skip-decorator` but not any of the other skip options, does that seem correct?

**Comment by tatomyr** [comment]
> What happens if the version isn't specified? Does the tool push to a new version, or the last known one?

We assume the default `latest` version.

> If I push to an existing API version without setting the upsert, would the push fail?

No, it is only needed when a user wants to create a new api from command line. For existing apis upsert changes nothing.

> could we make those available from command line as a quick lookup/listing

There're 2 main use cases: CI/CD and push from local machine. In CI/CD this doesn't make much sense since it most likely will be configured once. In the second case a user can simply define org & apis in the config file. 

> Are preprocessors applied at this step? Decorators? Linting? Bundling? 

At push step we bundle the definition. Respectively decorators and preprocessors are applied.

**Comment by lornajane** [comment]
Thanks for all the extra context! Even before we make changes, this helps me to understand how the command should be used.

So does upsert here mean create, so it would add a new entry to the API registry? Or is it more complicated, that means we need to make it this way? It seems like it is needed for insert but not for update.

**Comment by lornajane** [comment]
After today's discussion, there's not much appetite to make big changes to this little-used command. We agreed that a middle ground might be to re-cast the existing command to use parameters rather than optional arguments for branch and the composite destination field, and to update the usage instructions to make the recommended usage clear but not to refactor the arguments for clarity as we provide these to the users in the workflows interface. Old command usage should still be supported.

This also ties in with other confusing CLI design situations, like #1063. The recent change to error when an API isn't supplied may expose a few situations where this syntax is providing surprises.
