### ISSUE TITLE
Error on running "build-docs" with Docker

### ISSUE THREAD

**Issue by 0xERR0R** [Redocly/redocly-cli#1041]
**Describe the bug**

If I run the "build-docs" command with `redocly/cli` docker image, I get following error:

```
Found undefined and using theme.openapi optionsPrerendering docsError: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/@redocly/cli/lib/commands/build-docs/template.hbs'
```

If I run `redocly build-docs openapi.yaml` with installed version (via NPM), it runs without error.

**To Reproduce**
1. Given some openAPI file file
2. Execute ` docker run --rm -v $PWD:/spec redocly/cli:latest build-docs  openapi.yaml`
3. See error

**Expected behavior**

HTML page will be created.

**Logs**

```
Found undefined and using theme.openapi optionsPrerendering docsError: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/@redocly/cli/lib/commands/build-docs/template.hbs'
```

**OpenAPI definition**

3.0.1

**Redocly Version(s)**

1.0.0-beta.124

**Comment by lornajane** [comment]
Confirmed, I see the same error

**Comment by damianoneill** [comment]
Is there a version of the docker image that works?  I've tried all the version on hub and get the same issue. 

```
90f3fa3b0685: Pull complete
Digest: sha256:6138f524c7f9aa84c2d0cef6c82173551c8e29844cb9b91b9b90ba66ce45a3af
Status: Downloaded newer image for redocly/cli:v1.0.0-beta.115
Found undefined and using features.openapi options[ReDoc Compatibility mode]: Converting OpenAPI 2.0 to OpenAPI 3.0
Prerendering docsError: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/@redocly/cli/lib/commands/build-docs/template.hbs'

make: *** [build-docs] Error 1
```

**Comment by tatomyr** [comment]
Seems to affect only the `build-docs` command.

**Comment by tatomyr** [comment]
Fix is underway.

**Comment by damianoneill** [comment]
Thanks @tatomyr

**Comment by tatomyr** [comment]
Thank you @damianoneill for bringing attention! The fix will be available in the next release.
