### ISSUE TITLE
Improve product information and opt-out

### ISSUE THREAD

**Issue by lornajane** [Redocly/redocly-cli#1044]
**Is your feature request related to a problem? Please describe.**

We have a little anonymised data about how the command is used, but want to add more detail, for example whether a config file is used. We should also check what version a user has and notify if they are out of date.

Users should be able to opt-out of sending us this data, for example by setting an environment variable. This should be clearly documented (for example in the main README).

**Describe the solution you'd like**

Commands and switches (but no user-specific information)

**Describe alternatives you've considered**

Do nothing! Always an option, but currently we can't do much with the data and there's no opt-out.

**Comment by RomanHotsiy** [comment]
@tatomyr DM me if you need to discuss it in more details 🙏
