### ISSUE TITLE
Is x-tags schema extension supported by CE?

### ISSUE THREAD

**Issue by cykl** [Redocly/redocly-cli#1047]
**Is your feature request related to a problem? Please describe.**

I'm trying to display schema using x-tags as documented in https://redocly.com/blog/display-schemas/ and https://redocly.com/docs/api-reference-docs/specification-extensions/x-tags/.

However, it doesn't seem to work as I can see the tags in the rendered html by not the schemas.

It's clear that schemaDefinitionsTagName isn't available in CE but x-tags status is unclear to me. Thus, I'm wondering if this is a CE limitation, if I'm doing something wrong or if something is broken.

**Describe the solution you'd like**

Same behavior as documented.

**Describe alternatives you've considered**

None (I can provide more details about my specific use case but they are likely irrelevant to the general issue).

**Additional context**

**Comment by romanpryshliak** [comment]
Hi,

Currently, this feature is only supported in Redocly (our premium product). 

Please follow this issue regarding its implementation in Redoc (our open-source product):

https://github.com/Redocly/redoc/issues/2148
