### ISSUE TITLE
Environmental variables in markdown not replaced in bundle

### ISSUE THREAD

**Issue by web-fu** [Redocly/redocly-cli#1048]
**Is your feature request related to a problem? Please describe.**
In the documentation says that is possible to use environmental variables inside MD files:
https://redocly.com/docs/developer-portal/guides/environment-variables/#step-1-define-the-variable,
but it is not clear if redocly-cli replace them during bundling.
Also it is not clear how to write MDX files and include them in the project

**Describe the solution you'd like**
Would be great a step-by-step tutorial and complete source code example that show this feature

**Additional context**
I've tried to add environmental variables inside `/docs/info-description.md`

My `openapi.yaml` file:
```
openapi: 3.0.0
info:
  version: 1.1.0
  title: My API
  contact:
    email: info@my-company.com
    url: 'https://my-company.com'
  x-logo:
    url: 'my-company.com/logo.png'
  description:
    $ref: ../docs/info-description.md
```

My `/docs/info-description.md`

```
<a href="https://{{process.env.DOC_BUCKET}}.my-company.com/{{process.env.STAGE_NAME}}/{{process.env.APP_DOMAIN}}/files/myfile.pdf" target="_blank" download>
  Additional file</a>
```

My .env.development

```
DOC_BUCKET=my-bucket
APP_DOMAIN=my.app
STAGE_NAME=dev
```

**Comment by Orest-Yastremskyy** [comment]
Hi @web-fu 

Let us check it, please.

**Comment by Orest-Yastremskyy** [comment]
@web-fu 

Unfortunately, I was not able to replicate this issue from our side with the given example.

I have inserted both the aforementioned HTML link and markdown style link, they are working as expected. Here is my md file:

```
<a href="https://{{process.env.DOC_BUCKET}}.my-company.com/{{process.env.STAGE_NAME}}/{{process.env.APP_DOMAIN}}/files/myfile.pdf" target="_blank" download>
  Additional file</a>

Markdown link:

[basic markdown knowledge](https://{{process.env.DOC_BUCKET}}.my-company.com/{{process.env.STAGE_NAME}}/{{process.env.APP_DOMAIN}}/files/myfile.pdf)
```

And both links render correctly:

![image](https://user-images.githubusercontent.com/96121440/232754991-2889aa76-7223-46f7-99a7-5197ad27054c.png)

![image](https://user-images.githubusercontent.com/96121440/232755223-7700c26f-e83b-4833-b3cf-5b3c0a3963b4.png)

Thus, is there a chance you could provide us with additional details regarding this use-case?

**Comment by web-fu** [comment]
Hi, I am using redocly - cli without any premium subscription. 
I'm not sure if is a bug, or I miss some steps, so if you could provide a working demo I can check it.
Also, if you want I can create a repository, but I'm not sure this would be helpful

**Comment by Orest-Yastremskyy** [comment]
Hi @web-fu,

Kindly note, that the aforementioned environment variables are available only for our premium product (both API docs and developer portal). Since you are using only Redocly CLI, it is the expected behavior.

Hope it helps.
