### ISSUE TITLE
In OpeanAPI v3 it can be done like so:

### ISSUE THREAD

**Issue by Sandrakay49** [Redocly/redocly-cli#1064]
In OpeanAPI v3 it can be done like so:

```
      requestBody:
        content:
          application/x-www-form-urlencoded:
            example:
              client_id: a08bfa22-e6d6-11ed-891c-2ea11c960b3f
              code_challenge: 9Y__uhKapn7GO_ElcaQpd8C3hdOyqTzAU4VXyR2iEV0
```

_Originally posted by @einaralex in https://github.com/Redocly/redoc/issues/1212#issuecomment-1529163024_

**Comment by romanpryshliak** [comment]
Hi @Sandrakay49,

Could you provide more details regarding this matter? Is there anything we can assist you with?

**Comment by Sandrakay49** [comment]
0 what more do you guys need is sending me this  email everyday
And if you want to tell you find out who is hacking my phone and doing this
names is what I want cuz I'm tired of this everyday you got to say I'm
doing this because I am new at that side so I want to know who's doing it
sandra Rice

**Comment by Sandrakay49** [comment]
@romanpryshliak  CPS workers
