### ISSUE TITLE
Broken styles in build-docs output when migrating from redoc-cli

### ISSUE THREAD

**Issue by Enet4** [Redocly/redocly-cli#1073]
**Describe the bug**
When attempting to migrate from `redoc-cli` to `@redocly/cli`, I could not obtain a proper standalone HTML file of the documentation. Possibly due to the lack of suitable CSS stylesheets, everything gets jumbled up.

**To Reproduce**

Given a single OpenAPI yaml file named `api.yaml`:

```yaml
openapi: 3.0.0
info:
  description: |

    # Introduction
    This is an introduction.

    <!-- ReDoc-Inject: <security-definitions> -->

  version: 1.0.0
  title: Example title
paths:
  "/api/manage/user":
    post:
      tags: [ Management ]
      summary: "Add a new user"
      description: Creates a new user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - "email"
                - "password"
              properties:
                email:
                  type: string
                  description: "A unique e-mail address for the user"
                password:
                  type: string
                  minLength: 8
                  description: "The pass phrase for the user to authenticate"
                name:
                  type: string
                  description: "The display name for the user"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: ["success"]
                  message:
                    type: string
components: {}
```

And this npm package:

```json
{
  "name": "use-redoc",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "build-html": "redocly build-docs api.yaml -o dist/API.html",
    "build-html-legacy": "redoc-cli bundle api.yaml -o dist/API.html",
    "preview": "redocly preview-docs api.yaml"
  },
  "dependencies": {
    "@redocly/cli": "^1.0.0-beta.126",
    "redoc": "^2.0.0",
    "redoc-cli": "^0.13.21"
  }
}
```

I ran the `build-html` command above:

```none
npx @redocly/cli build-docs api.yaml -o dist/API.html
```

To see this when opening the HTML file:

![Screenshot of the problem](https://github.com/Redocly/redocly-cli/assets/4738426/66ce2b3f-0b80-49bf-a071-1a8522e4488b)

I originally did not have a `redocly.yaml` file, so I created one based on the starter project as an attempt to fix these issues:

```yaml
apis:
  sample@v1: 
    root: api.yaml
extends:
  - recommended
rules:
  no-unused-components: error
theme:
  openapi:
    htmlTemplate: ./index.template.html
    theme:
      colors:
        primary:
          main: "#32329f"
    generateCodeSamples:
      languages:
        - lang: curl
```

Along with this template HTML file named `index.template.html`:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>API Reference | ReDoc</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <style>
      body {
        margin: 0;
        padding: 0;
      }
    </style>
    {{{redocHead}}}
  </head>
  <body>
    {{{redocHTML}}}
  </body>
</html>
```

But the outcome was the same as the screenshot above.

**Expected behavior**

The command which I used in `redoc-cli` provides the expected result.

```none
redoc-cli bundle api.yaml -o dist/API.html
```

![Screenshot without the problem](https://github.com/Redocly/redocly-cli/assets/4738426/c9f34d43-929e-4be1-a06b-ec12b0715805)

It is more bizarre that the _preview_ obtained through `redocly preview-docs` also shows the document correctly. The problem occurs specifically with `build-docs`.

**Logs**

There doesn't seem to be much going on at the docs.

```none
λ npm run build-html

> use-redoc@0.1.0 build-html
> redocly build-docs api.yaml -o dist/API.html

Found redocly.yaml and using theme.openapi options
Prerendering docs
🎉 bundled successfully in: dist/API.html (15 KiB) [⏱ 21ms].
```

**Redocly Version(s)**: `1.0.0-beta.126`

**`Node.js` Version(s)**: Reproduced both with 16.20.0 and 18.16.0

**Additional context**

This is the same effect as the one reported in Redocly/redoc#2212, although it only happens when using the non-deprecated tools.

**Comment by tatomyr** [comment]
Thanks for reporting the issue!

**Comment by lornajane** [comment]
Something interesting is going on here, I have no explanation yet but I'll add my observations, because I can replicate, and it's strange.

Using the `api.yaml` and `package.json` from above:

Running `npm run build-html` produces the following:

```
$ npm run build-html

> use-redoc@0.1.0 build-html
> redocly build-docs api.yaml -o dist/API.html

Found undefined and using theme.openapi options
Prerendering docs
🎉 bundled successfully in: dist/API.html (15 KiB) [⏱ 1829ms].
```

The result is unstyled, and I'd like you to note the filesize.

Using `npx` gives the same result:

```
$ npx @redocly/cli build-docs api.yaml -o dist/API.html
Found undefined and using theme.openapi options
Prerendering docs
🎉 bundled successfully in: dist/API.html (15 KiB) [⏱ 1620ms].
```

However if I use the `redocly` command directly:

```
$ redocly build-docs api.yaml -o dist/API.html
Found undefined and using theme.openapi options
Prerendering docs
🎉 bundled successfully in: dist/API.html (50 KiB) [⏱ 1708ms].
```

The generated HTML file has a large additional `<style>` tag in the source, which explains the larger file size, and the output looks exactly as I would expect it to.

I'm unclear why running the command by itself is different from when it is wrapped by `npm` though, hoping some of the JS experts will have some suggestions. It might also be that I have different global dependencies in place, or I'm doing something else differently.

**Comment by tatomyr** [comment]
Hi @Enet4,

I was poking around a bit and I figured out the issue was some inconsistency with **styled-components** versions when installing the packages. Installing a specific version helped me: `npm i styled-components@5.3.3`. Could you check if that resolves the issue on your end?

Another solution was to remove **package-lock.json** + `node_modules` and installing packages using node 18 / npm 9.

**Comment by tatomyr** [comment]
Hi @Enet4,

Could you check if the issue has gone with the `v1.0.0-beta.130`?

**Comment by Enet4** [comment]
@tatomyr Yes, I confirm that the problem is gone! Much appreciated!
