### ISSUE TITLE
The regular expression "^[a-zA-Z0-9\.\-_]+$" should only be applied to fixed-fields under component

### ISSUE THREAD

**Issue by ZyzychO** [Redocly/redocly-cli#1104]
Examples map keys defined in components must adhere to a pattern: '^[a-zA-Z0-9._-]+$'. (Source: https://github.com/OAI/OpenAPI-Specification/blob/main/schemas/v3.1/schema.yaml)

However, no such restrictions are defined on the examples map defined inside of a media-type object.

```
openapi: 3.0.0
info:
  title: Sample API
  description: Optional 
  version: 0.1.9

paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses: 
        '200': 
          description: OK
          content: 
            application/json: 
              schema: 
                type: object
              examples:
                My valid example:
                  value: 
                    foo: bar
                A_valid_example:
                  value: 
                    baz: quz   
```
As you can see on the example above, the name of the example `My valid example` will be defined as invalid by rule:  **spec-components-invalid-map-name**.
<img width="1063" alt="Screenshot 2023-05-26 at 00 06 16" src="https://github.com/Redocly/redocly-cli/assets/106024790/4edf960d-9744-407b-ad67-de295770f1d6">
[example-yaml.yaml.zip](https://github.com/Redocly/redocly-cli/files/11569417/example-yaml.yaml.zip)

**Expected behavior**

rule: **spec-components-invalid-map-name** should apply only to the fixed fields under the components, this restriction should not apply to examples mapped inside of a media-type object

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_alhxo)

**Comment by IgorKarpiuk** [comment]
@ZyzychO We added this to resolve issue https://github.com/Redocly/redocly-cli/issues/959. Do we need to change this behavior?

@tatomyr

**Comment by tatomyr** [comment]
@IgorKarpiuk I believe we should comply with the specification. If someone wants additional restrictions, they may use a custom rule.

**Comment by adamaltman** [comment]
@IgorKarpiuk that example is correct and the behavior should stay the same for components. The sample file provided for #959 though didn't include inline examples defined within paths.

```yaml
components: { it should check here }
paths: { it should not apply here }
```

**Comment by IgorKarpiuk** [comment]
@adamaltman @lornajane  should we validate only top level keys in components? The specification does not tell anything about the nested keys: https://spec.openapis.org/oas/v3.1.0#components-object

**Comment by lornajane** [comment]
Great question! Yes, I think we have to limit this check to the keys inside the fixed fields in components.

It looks like it would technically be valid (although probably unwise) to use a key with spaces in it in JSON Schema, and as you correctly point out, the spec does not actually state that the rules apply beyond the first level keys. Perhaps we can add a rule example for making your keys match sane patterns - I suspect the spaces, even if valid in OpenAPI, would trip up plenty of tools, so users might want to add that for their own sanity.
