### ISSUE TITLE
Build Docs HTML has dependencies

### ISSUE THREAD

**Issue by MelleD** [Redocly/redocly-cli#1105]
**Describe the bug**
When I use `build-docs` with the redocly, there is always a dependency on cdn in the header.
`<script src="https://cdn.redoc.ly/redoc/v2.0.0/bundles/redoc.standalone.js"></script>`

**To Reproduce**
1. Given this `redocly.yaml` file
2. And this OpenAPI file(s)
```
---
openapi: 3.0.3
info:
  title: Test
  version: v1
  description: Test
paths:
  /test:
    get:
```
4. Run this command with these arguments... `redocly ...`
```
@redocly/cli/bin/cli.js
                              build-docs test.yaml
                              -o test.html
                              --title 'API documentation'
```

5. See error
```
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf8" />
  <title>API documentation</title>
  <!-- needed for adaptive design -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    body {
      padding: 0;
      margin: 0;
    }
  </style>
  <script src="https://cdn.redoc.ly/redoc/v2.0.0/bundles/redoc.standalone.js"></script

...
```

**Expected behavior**
Possibility to give a own javascript tag into the {`{{redocHeader}}}` or a option to embed the javascript like in the previous version.

The issue looks here:
https://github.com/Redocly/redocly-cli/blob/main/packages/cli/src/commands/build-docs/utils.ts

`export async function getPageHTML`

This can be a problem if you have strict content security policies. There should be a way to host all resources yourself

**OpenAPI definition**
```
---
openapi: 3.0.3
info:
  title: Test
  version: v1
  description: Test
paths:
  /test:
    get:
```

**Redocly Version(s)**
1.0.0-beta.126

**`Node.js` Version(s)**
9.6.7

**Comment by Orest-Yastremskyy** [comment]
Hi @MelleD,

Thank you for sharing this.

We already have a similar ticket opened: https://github.com/Redocly/redocly-cli/issues/1035.
Feel free to provide any additional details to the aforementioned ticket.

**Comment by MelleD** [comment]
@Orest-Yastremskyy  thanks for the hint :)
