### ISSUE TITLE
Plans on supporting AsyncAPI?

### ISSUE THREAD

**Issue by tino-prahl** [Redocly/redocly-cli#1126]
Currently we are using Redocly CLI for bundling and linting our OpenAPI spec files.
We also providing some of our guidelines as linter rules: https://github.com/otto-de/api-guidelines/#api-linting

In the future we might want to lint our AsyncAPI spec files and also add custom linter rules.

Are you planning to support [AsyncAPI](https://www.asyncapi.com/)?

Thanks! I'd love to hear back from you.

**Comment by RomanHotsiy** [comment]
Yes, we plan to support it. But after 1.0 release.

There was some progress on it but we don't have time to finish it faster: https://github.com/Redocly/redocly-cli/pull/1127

**Comment by adamaltman** [comment]
@tino-prahl and @birgitbader did a great job with API guidelines and implementing corresponding lint rules to enforce them. Maybe there would be some interest to share more content about this with the world?

The world needs more shining examples like this one to help inspire and guide them. Thanks.

**Comment by lornajane** [comment]
@tino-prahl out of curiosity, which bindings do you use in AsyncAPI? I'm chipping away at that branch that @RomanHotsiy shared and might have something for you to play with in the coming weeks.
