### ISSUE TITLE
redocly/cli docker image does not work generates error for missing file

### ISSUE THREAD

**Issue by WesternStar** [Redocly/redocly-cli#1144]
**Describe the bug**
redoc-cli image doesn't work with build error is
Found undefined and using features.openapi options[ReDoc Compatibility mode]: Converting OpenAPI 2.0 to OpenAPI 3.0
Prerendering docsError: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/@redocly/cli/lib/commands/build-docs/template.hbs'

**Expected behavior**
Expected the doc generation for redoc cli to work
**Minimal reproducible OpenAPI snippet(if possible)**
This doesn't seem to work on the last two images as well as the oldes image
docker run -v  <host_path>:<docker path>  -v <host_output>:<docker_output> harbor.cloud.aurora.tech/dockerhub/redocly/cli:v1.0.0-beta.115 build-docs <docker_output>
 - o <docker_output>
 **Screenshots**

**Additional context**
This is related to the bug https://github.com/Redocly/redoc/issues/1537 but there doesn't seem to be any image that will work for the ones put on docker

**Comment by tatomyr** [comment]
Hi @WesternStar,

Could you try the latest version of @redocly/cli?

**Comment by WesternStar** [comment]
I have been trying it 
```
amcnair@amcnair-vdesk ~/c/av (WesternStar/grpc_gateway_openapi) [1]> docker run -v   ./bazel-bin/experimental/amcnair/grpc_gateway/_virtual_impor
ts/data_reader_api/experimental/amcnair/grpc_gateway/data_reader.swagger.json:/bazel-bin/experimental/amcnair/grpc_gateway/_virtual_imports/data_
reader_api/experimental/amcnair/grpc_gateway/data_reader.swagger.json -v ~/redoc_output:/redoc_output harbor.cloud.aurora.tech/dockerhub/redocly/
cli:latest build-docs /bazel-bin/experimental/amcnair/grpc_gateway/_virtual_imports/data_reader_api/experimental/amcnair/grpc_gateway/data_reader
.swagger.json --output=/redoc_output/index.html
Found undefined and using theme.openapi options
[ReDoc Compatibility mode]: Converting OpenAPI 2.0 to OpenAPI 3.0
Prerendering docsError: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/@redocly/cli/lib/commands/build-docs/template.hbs'
```
We use a pull through cache via harbor but it is the latest version of the cli.

**Comment by tatomyr** [comment]
Could you check what the latest version of the Redocly CLI image is on harbor? I cannot register there for some reason.

**Comment by WesternStar** [comment]
Good catch it wasn't in the cache so it was pulling the version before that.
