### ISSUE TITLE
How to alphabetically sort yamls generated by bundle command

### ISSUE THREAD

**Issue by PhilippGeers** [Redocly/redocly-cli#1145]
Hello, 
is there a way to automatically sort the schemas in a bundle generated `openapi.yaml` file alphabetically ?
When I want to combine my many referencing yamls using `redocly bundle composed_refs.yaml > openapi.yaml` it seems that the references from the many referencing yamls are not listed alphabetically under `components > schemas`. The goal would be for the generated file from the bundle command to automatically have alphabetically sorted schemas.

so far i could not find a cli option to make this possible.

**Comment by lornajane** [comment]
This is a good question, and right now there isn't a way to do that. We have the setting `sortOperationsAlphabetically` to use when generating reference docs, but this doesn't exist for the API descriptions themselves. I'll leave this open for discussion.

**Comment by tatomyr** [comment]
Will a [custom decorator](https://redocly.com/docs/cli/custom-plugins/custom-decorators/) help here?

**Comment by lornajane** [comment]
I have one for tags, I can adapt it for this as well (but not today!)

**Comment by lornajane** [comment]
I'm including some files for a custom decorator, in case this is useful. The decorators are part of the `bundle` command, allowing you to make changes to your API description. The files I'm listing are:
* `redocly.yaml` showing an example of how to include the plugin and enable the decorator
* `sorting.js` is the custom plugin
* `component-schemas-sorting.js` adds the functionality to sort the schemas (@tatomyr I'd appreciate your review on this part if possible!)

It might be useful to take a look at [our custom plugin documentation](https://redocly.com/docs/cli/custom-plugins/) as well.

`redocly.yaml`:
```
plugins:
  - './sorting.js'

decorators:
  sorting/component-schemas-alphabetical: on
```

`sorting.js`
```
const SortSchemasAlphabetically = require('./component-schemas-sorting');

module.exports = {
  id: 'sorting',
  decorators: {
    oas3: {
      'component-schemas-alphabetical': SortSchemasAlphabetically,
    }
  }
}
```

`component-schemas-sorting.js`
```
module.exports = SortSchemasAlphabetically

function SortSchemasAlphabetically() {
  console.log("re-ordering components.schemas: alphabetical");
  return {
    NamedSchemas: {
      leave(schemas) {
        // get schema names and sort them
        const keys = Object.keys(schemas);
        keys.sort();

        // cache the data into another object
        // shallow clone is fine since we're only switching keys around
        oldSchemas = Object.assign({}, schemas);

        // delete and re-add keys into the object in alphabetical order
        for (let i=0; i< keys.length; i++) {
          delete schemas[keys[i]];
          schemas[keys[i]] = oldSchemas[keys[i]];
        }
      }
    }
  }
}
```

**Comment by tatomyr** [comment]
> component-schemas-sorting.js adds the functionality to sort the schemas

Yes, this solutions works.

**Comment by lornajane** [comment]
I think this question was answered, so I'll close the issue but let us know if you need anything else!
