### ISSUE TITLE
push --files option seems not upload extra files anymore

### ISSUE THREAD

**Issue by mto-gambit** [Redocly/redocly-cli#1148]
**Describe the bug**

Starting version `1.0.0-beta.129` `--files` options of `push` command doesn't seems to upload other files 

**To Reproduce**

1. Given no `redocly.yaml` file
2. And any OpenAPI file
3. Run `push` command the following arguments ` .\my-api.yaml @organization-id/api-id@version-id --upsert --files .\docs\`
4. Extra files in ./docs are not pushed.

**Expected behavior**

files from `--files` options are uploaded to registry.

**Logs**

Here's a comparison between versions `128` and `129`

npx @redocly/cli@1.0.0-beta.128 push .\my-api.yaml @organization-id/api-id@version-id --upsert --files .\docs\

    ╔═══════════════════════════════════════════════════════════════╗
    ║                                                               ║
    ║  A new version of Redocly CLI (1.0.0-beta.129) is available.  ║
    ║  Update now: `npm i -g @redocly/cli@latest`.                  ║
    ║  Changelog: https://redocly.com/docs/cli/changelog/           ║
    ║                                                               ║
    ╚═══════════════════════════════════════════════════════════════╝
  Bundling definition
Created a bundle for .\my-api.yaml
Uploading 2 files:
Uploading bundle for <filetree>\my-api.yaml...✓ (1/2)
Uploading <filetree>\docs\my-docs.md...✓ (2/2)

Definition: .\my-api.yaml is successfully pushed to Redocly API Registry

npx @redocly/cli@1.0.0-beta.129 push .\my-api.yaml @organization-id/api-id@version-id --upsert --files .\docs\
Deprecation warning: Do not use the second parameter as a destination. Please use a separate --destination and --organization instead.

Bundling definition
Created a bundle for .\my-api.yaml
Uploading 1 file:
Uploading bundle for <filetree>\my-api.yaml...✓ (1/1)

Definition: .\my-api.yaml is successfully pushed to Redocly API Registry

**Redocly Version(s)**

1.0.0-beta.129

**`Node.js` Version(s)**

v18.16.0

**Additional context**

using the new options (--destination and --organization) do not solve the issue.

**Comment by IgorKarpiuk** [comment]
Hi @mto-gambit,  thanks for the reporting.

Will be fixed in the next release.
