### ISSUE TITLE
Update dependency styled-components to v6

### ISSUE THREAD

**Issue by smorimoto** [Redocly/redocly-cli#1163]
**Is your feature request related to a problem? Please describe.**

We'd like to use a consistent version in a massive monorepo, but currently Redocly relies on a deprecated API of styled-components.

**Describe the solution you'd like**

Just update dependency styled-components to v6. In fact, it was changed to peer dependency in a recent release, so dropping support for v5 by update the peer dependency version constraint is not required and avoid using a deprecated API is just enough.

**Describe alternatives you've considered**

Not applicable.

**Additional context**

```
/home/runner/work/REDACTED/REDACTED/node_modules/redoc/bundles/redoc.lib.js:646
`,Vi=ee(Qi.withComponent("pre"))`
            ^

TypeError: Qi.withComponent is not a function
    at /home/runner/work/REDACTED/REDACTED/node_modules/redoc/bundles/redoc.lib.js:646:12
    at /home/runner/work/REDACTED/REDACTED/node_modules/redoc/bundles/redoc.lib.js:1807:3444
    at /home/runner/work/REDACTED/REDACTED/node_modules/redoc/bundles/redoc.lib.js:1807:3449
    at /home/runner/work/REDACTED/REDACTED/node_modules/redoc/bundles/redoc.lib.js:2:81
    at Object.<anonymous> (/home/runner/work/REDACTED/REDACTED/node_modules/redoc/bundles/redoc.lib.js:2:191)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
```

**Comment by smorimoto** [comment]
Maybe this issue should be cross-referenced with https://github.com/Redocly/redoc/issues/2336.

**Comment by smorimoto** [comment]
By the way, this still happens while executing the bundle command even with the `v1.0.0-beta.130`.

**Comment by lornajane** [comment]
Thanks for this suggestion and context. I think is also related to the discussion in #1159

**Comment by lornajane** [comment]
This should be fixed in newer releases. @smorimoto could you let us know if this is still causing a problem?

**Comment by tatomyr** [comment]
I'm closing this one as the `styled-components` package dependency has already been updated. Feel free to open a new issue or comment here if this is still a problem.
