### ISSUE TITLE
Can you specify the order plugins run in relation to each other?

### ISSUE THREAD

**Issue by michaelgwelch** [Redocly/redocly-cli#1194]
**Describe the bug**

This may not be a bug. Likely isn't a bug. It's a question that I can't find any documentation on. We are upgrading from 1.0.0-beta.111 to the new release version 1.0.0.

We have two preprocessor plugins that we've developed and have been using with the beta versions for the last 2 years or so. They've been working great.

The first allows us to write something like this instead of a `description`

```yaml
get: 
  operationId: getSomething
  summary: Get Something
  x-description-ref:
    $ref: ../description.md
  # We used an x-description-ref rather than a `definition` 
```

Which allows us to type a longer description right in a markdown file. The plugin then resolves the reference to the file and puts the contents of the file as the value of a `description` and then deletes the `x-description-ref` key.

The second is called `replace-macros` and it replaces constants like `_OUR_MACRO_` with a predetermined string. (I would imagine something like this is already built into redocly and maybe we don't need this plugin any more?)

The first is configured to run on `enter` of a node and the second one is configured to run on `leave` of a node. It's important that for each relevant node that the `replace-macro` run after the other preprocessor. If it doesn't then none of the macros in the referenced file will get replaced.

What is the algorithm for running plugins? Do you run them sequentially? If so, can they be ordered? Or alternatively do they get interleaved?

What we are seeing is that all of `replace-macros` runs first before the first invocation of the `x-description-ref` plugin.

If we revert back to the old version it continues to work as desired.

**Comment by RomanHotsiy** [comment]
It should work in the order you expect. `enter` should be always executed before `leave`. Something must be wrong.

Could you share more details on your preprocessors? The code of the plugin would be amazing but if you can't share it for some reason then the general layout would be enough.

**Comment by RomanHotsiy** [comment]
> Do you visit the graph multiple times: once for each plugin? Or do you visit the graph just one time and on each node you run the skip, then enter then leave methods of each visitor?

The latter one is how we do it.

> "visit the graph just one time and on each node you run the skip, then enter then leave methods of each visitor".

But we do separate traversal for every stage: preprocess, lint, decorate. Are both of your visitors registered as preprocessors indeed?
This is the only reason I can think of for the behaviour you observe (other than us having some bug for sure 😄).

If they are, could you please share some minimal reproducible sample please?

**Comment by lornajane** [comment]
We haven't had an update on this for a while so I'll close, but please let us know if you have more information on this one. If we can replicate it, we'll take another look.
