### ISSUE TITLE
no 'no-ambiguous-paths' error between Get:/user/config  and Get:/user/{userId}

### ISSUE THREAD

**Issue by luania** [Redocly/redocly-cli#1204]
**Describe the bug**
lint this oas file reports no error

**To Reproduce**
redocly lint openapi.yaml

**Expected behavior**

report no-ambiguous-paths error

**Logs**

```sh
validating openapi.yaml...
openapi.yaml: validated in 15ms

Woohoo! Your OpenAPI definition is valid. 🎉
```

**OpenAPI definition**

```yaml
# openapi.yaml
openapi: 3.0.3
info:
  contact:
    name: test
  title: pieclouddb-operation
  version: '1.0'
servers:
  - url: 'http://localhost:8088/api/v1'
paths:
  /user/config:
    get:
      summary: get user config
      operationId: get-user-config
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: string
  /user/{userId}:
    parameters:
      - schema:
          type: string
        name: userId
        in: path
        required: true
    get:
      summary: get user info by userId
      operationId: get-user-userId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: string
```

**Redocly Version(s)**

1.0.0-beta.125

**`Node.js` Version(s)**

v16.16.0

**Comment by lornajane** [comment]
Thanks for letting us know about this, I have a couple of follow up questions:
- do you have a `redocly.yaml` file? There was a change in an earlier beta version to stop choosing a default ruleset when there's a config file present.
- does the same thing happen with the newest release 1.0.0? This version will also warn you if no rules are supplied, which can help to catch configuration problems.

**Comment by luania** [comment]
> Thanks for letting us know about this, I have a couple of follow up questions:感谢您让我们知道这一点，我有几个后续问题：
> 
> * do you have a `redocly.yaml` file? There was a change in an earlier beta version to stop choosing a default ruleset when there's a config file present.你有 `redocly.yaml` 文件吗？早期测试版本中进行了更改，当存在配置文件时停止选择默认规则集。
> * does the same thing happen with the newest release 1.0.0? This version will also warn you if no rules are supplied, which can help to catch configuration problems.最新版本 1.0.0 是否会发生同样的情况？如果未提供规则，此版本还会向您发出警告，这有助于发现配置问题。

- my redocly.yaml
```yaml
extends:
  - recommended
rules:
  no-ambiguous-paths: error
  info-license: off
  operation-4xx-response: off
  security-defined: off
```
- This also happens with version 1.0.0

**Comment by luania** [comment]
It seems that the spec feels that these two paths are not ambiguous?
https://github.com/OAI/OpenAPI-Specification/issues/2564

**Comment by tatomyr** [comment]
Your example is valid according to [our documentation](https://redocly.com/docs/cli/rules/no-ambiguous-paths/). However, you may want to write a [custom rule](https://redocly.com/docs/cli/resources/custom-plugins/#custom-rules) for this specific case. 

I'm closing the issue since it isn't a bug. Feel free to reopen it if you think it should be an enhancement.

**Comment by tatomyr** [comment]
As it stands from the [docs](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.0.md#patterned-fields), such paths are resolved in a certain order: 

> When matching URLs, concrete (non-templated) paths would be matched before their templated counterparts.

Thus, the paths from your example aren't ambiguous. 

You can use a custom rule if you still want to avoid those cases. 

Cheers!
