### ISSUE TITLE
Add $ref support in redocly.yaml

### ISSUE THREAD

**Issue by tatomyr** [Redocly/redocly-cli#1219]
More details: https://github.com/Redocly/redocly/issues/3280

Additionally, it worth checking if we can improve $ref pointer resolution (see [a comment](https://github.com/Redocly/redoc/issues/740#issuecomment-1670740699)).

**Comment by RomanHotsiy** [comment]
@tatomyr I raised it to p1. This is blocking one of our customers. They want to use it for `rules`.

Also, we had to implement custom resolution in our cloud which is not ideal and we hit bugs with that.

Also, make sure it works in VS Code extension.

**Comment by lornajane** [comment]
Thanks for the update @RomanHotsiy . Do you have an example of what we're aiming for? I don't think I exactly understand why including a ruleset wouldn't be an option here, and this seems like a good time to ask questions!

**Comment by RomanHotsiy** [comment]
They want to be able to do something like this:

`redocly.yaml`:

```yaml
extends: [minimal]
# ...
rules:
  $ref: rules.yaml
```

You are right. I believe using a rule set in extends would solve it for them.

`redocly.yaml`:

```yaml
extends: [minimal, "./rules.yaml"]
```

Is it what you meant?

Although we still need $ref support for other places like `redirects`, `sso`, etc. See the linked issue.

**Comment by lornajane** [comment]
Yes that's what I meant - just in case we can unblock a customer with that workaround. However this will be a really good feature for all the other reasons you mentioned and probably a bunch of other things I didn't think of yet!

**Comment by RomanHotsiy** [comment]
Yes! Thanks. This is a great suggestion. I'll let them know!
