### ISSUE TITLE
preview-docs and build-docs do not include tag-description-override decorators

### ISSUE THREAD

**Issue by halindrome** [Redocly/redocly-cli#1244]
**Describe the bug**

I have a simple redocly.yaml file that has one `tag-description-override` section for an API.  This works fine when using bundle to generate followed by build-docs or preview-docs:

```
# redocly bundle -o /tmp/thebundle.yaml path/to/spec.json
# redocly build-docs /tmp/thebundle.yaml
```

However, simply calling preview-docs or build-docs on the same path/to/spec.json does not include the overrides referenced by the decorators.   

This wouldn't matter if the `tag` allowed a `$ref` in its description, or if there was some extension like `x-description-ref` that allowed a ref.   

And yes, I am aware that I could embed the CommonMark in the spec directly. However, we use JSON for the majority of our specifications and embedding CommonMark in JSON is at best painful.

**To Reproduce**

1. Given this `redocly.yaml` file

```
# See https://redocly.com/docs/cli/configuration/

apis:
  # Update the apiName with your actual API name, and the version with your actual API version.
  Example@2:
    root: ./openapi.json
    rules:
      operation-4xx-response: off
      tag-description: off
      no-empty-servers: off
      security-defined: off
      info-license: off
    decorators:
      tag-description-override:
        tagNames:
          Example: ./EXAMPLE.md

extends:
  - recommended

theme:
  openapi:
    generateCodeSamples:
      languages:
        - lang: curl
        - lang: Node.js
        - lang: Python
```

2. And this OpenAPI file(s)

```
{
  "openapi" : "3.1.0",
  "info" : {
    "title" : "Example",
    "version" : "1.0",
    "summary" : "Example summary"
  },
  "components" : {
  },
  "paths" : {
    "/example":
    {
      "get" : {
        "operationId" : "example",
        "responses" : {
          "200" : {
            "content" : {
              "application/json" : {
                "schema": {
                "properties": {
                  "status": { "type": "string" }
                },
                "required": [
                  "status"
                ],
                "type": "object"
              }
              }
            },
            "description" : "Succeeded"
          }
        },
        "summary" : "Example summary",
        "tags" : [
          "Example"
        ]
      }
    }
  },
  "tags" : [
    {
      "name" : "Example"
    }
  ]
}
```
3. And this external description EXAMPLE.md
```
# An Example Description

This is a CommonMark description of the example tag.
```
4. Run this command with these arguments... `redocly bundle` and you will see the external file included
5. Run this command with these arguments... `redocly build-docs` and examine the generated redoc-static.html file
6. The external file contents are not included

**Expected behavior**

I would expect the external referenced files to be included.

**OpenAPI definition**

Using OpenAPI 3.1.0

**Redocly Version(s)**

1.0.2

**`Node.js` Version(s)**

14.15.5

**Comment by SmoliyY** [comment]
Hi @halindrome, thanks for reporting! This is the same issue as #1078. 
By the way, maybe provided [solution](https://github.com/Redocly/redocly-cli/issues/1078#issuecomment-1547430617) can help you?

**Comment by halindrome** [comment]
Thank you - yes, a similar work around has been implemented by us locally. A real fix would be nice, since without it the VS Code plugin and associated preview option is somewhat confusing.

**Comment by SmoliyY** [comment]
Good point! I am going to attach this issue to the VS Code extension too!

**Comment by lornajane** [comment]
I think this is a really good fit for the VSCode extension, but that the commands in the CLI should remain separate; the functionality is correct as it stands, but we're also working on some changes to make it easier to combine multiple steps. I'll close this specific issue, since we won't add decorators into the `build-docs` step.
