### ISSUE TITLE
Incorrect validation error "Example validation errored: schema with key or id ... already exists"

### ISSUE THREAD

**Issue by ehuelsmann** [Redocly/redocly-cli#1245]
In the attached YAML schema [API.yaml.gz](https://github.com/Redocly/redocly-cli/files/12433360/API.yaml.gz), the following error is consistently reported:

Example validation errored: schema with key or id "/tmp/tmp.odmvjRGLjU/API.yaml#/components/schemas/commonId" already exists.

1406 | application/json:
1407 |   schema:
1408 |     $ref: '#/components/schemas/Warehouse'
1409 |   examples:
1410 |     validWarehouse:

referenced from API.yaml:1407:15 at #/paths/\~1products\~1warehouses\~1{id}/get/responses/200/content/application\~1json 

Warning was generated by the no-invalid-media-type-examples rule.

API.yaml: validated in 242ms

However, the schema component id "commonId" appears exactly once in the specification. There is also no overlap between the "allOf" elements in the type being validated.

**To Reproduce**

1. Unpack the attached API.yaml
2. Run px @redocly/cli lint API.yaml

Will show the error above.

**Expected behavior**

I'm expecting the file to validate without errors. (There are no problems in the examples of this file as far as I can verify.)

**Logs**

None.

**OpenAPI definition**

Spec 3.0.3.

**Redocly Version(s)**

$ npx @redocly/cli --version
1.0.0-beta.125

**`Node.js` Version(s)**

$ node --version
v18.16.0

**Additional context**

None that I know of.

**Comment by Orest-Yastremskyy** [comment]
Hi @ehuelsmann 

Thank you for reaching out.

We were able to replicate this issue and it appears to be a bug.

Please note that we will notify you as soon as the issue is resolved.

**Comment by tatomyr** [comment]
Hi @ehuelsmann, the fix is already available in Redocly CLI 1.7. Could you confirm the issue has been resolved?

**Comment by ehuelsmann** [comment]
@tatomyr, just verified with Redocly CLI 1.8: the problem is indeed gone!

Thank you so much!
