### ISSUE TITLE
Output of bundle isn't a valid JSON/YAML file

### ISSUE THREAD

**Issue by lornajane** [Redocly/redocly-cli#1249]
**Describe the bug**

When running `redocly bundle`, the output file should be produced to stdout if the `--output` parameter isn't supplied. Nothing else should be going to stdout, but it seems like it does (or can do) in some cases.

The user should be able to pipe the output to another tool (grep, another redocly command, whatever), so the output must be valid JSON/YAML.

Any other output should be sent to stderr, visible to the user using the terminal, but not ending up in the output stream.

**Unsolved mystery needs more research** How does/should this work with multiple bundle files, either specified in the command, supplied as a glob, or described in the config file?

**Comment by jeremyfiel** [comment]
i wonder if this should only output a file rather than to stdout. a bundle dereferenced could be massive and cause a bunch of other issues, especially with a glob pattern (the way we are using it).

**Comment by lornajane** [comment]
Thanks for the input! The output file is definitely the primary use case, but it's not the only one. I'd like us to support stdout for single files (do you have a simple example of your glob usage?) as well. Very large files aren't a problem for bundle, but currently the command does do a few things that could choke something like `jq` if it's the next command in the chain.

**Comment by jeremyfiel** [comment]
Our glob is typically a full directory.  `specs/**/*swagger*`  ~1200 descriptions are validated

**Comment by lornajane** [comment]
@philsturgeon do you have a replication case for this? We talked about it, but I can't now provoke anything that isn't yaml to come out of stderr and into the next stage of the process. Any tips?

**Comment by lornajane** [comment]
Closing since we don't have a clearly defined bug to fix, let's re-open if we get more information.
