### ISSUE TITLE
Drop linting option from bundle command

### ISSUE THREAD

**Issue by lornajane** [Redocly/redocly-cli#1250]
**Is your feature request related to a problem? Please describe.**

The bundle command includes some confusing options (format) that can apply to the linting part of the command. This also produces confusing output because bundle should output a single API description, and linting outputs some error/warning feedback (or the sucess message).

**Describe the solution you'd like**

Since we see very little usage of bundle combined with lint, please drop the option to add linting to the bundle command, and encourage users to run these steps separately (will need docs updates as well as tools changes).

I think this means we need to:
- [ ] Remove `--format` option (this relates to problem reporting)
- [ ] Remove `--max-problems` (this relates to problem reporting)
- [ ] Remove `--skip-rule` (rules aren't used when bundling)
- [ ] Remove `--lint`
- [ ] Remove `--extends` (rulesets aren't used when bundling)
- [ ] Update related documentation for bundle command
- [x] Add a guide on linting and then bundling (we'll edit this if we add command chaining support) #1385 
- [ ] If a user users any of the removed options, let them know to use the commands separately and link to the guide.

**Describe alternatives you've considered**

Require filenames only. But command chaining is an expected feature of CLI tools, so I think we should support it and adjust the tools accordingly.

**Comment by tatomyr** [comment]
Related: https://github.com/Redocly/redocly-cli/issues/1397.
