### ISSUE TITLE
OpenAPI 3.1 License object warning

### ISSUE THREAD

**Issue by SergeAx** [Redocly/redocly-cli#1282]
**Describe the bug**

OpenAPI spec 3.1 (see https://spec.openapis.org/oas/v3.1.0#licenseObject) says:

"The url field is mutually exclusive of the identifier field"

However, if I put an identifier field into my license, I am getting a warning that `url` field should be included.

**To Reproduce**

Given this minimal OpenAPI file `test.yaml`:

```yaml
openapi: "3.1.0"
servers:
  - url: http://localhost

info:
  version: 0.1.0
  title: Example
  license:
    name: MIT
    identifier: MIT

security:
  - {}

paths:
  /:
    options:
      operationId: options
      summary: options
```

Run this command `redocly/cli lint test.yaml`

See warning:

`License object should contain url field.`

**Expected behavior**

According to OpenAPI 3.1 spec, `url` field must be omitted if `identifier` field is present in `info` -> `licence` object.

**Logs**

```
validating test.yaml...
[1] test.yaml:8:3 at #/info/license/url

License object should contain `url` field.

 6 | version: 0.1.0
 7 | title: Example
 8 | license:
   | ^^^^^^^
 9 |   name: MIT
10 |   identifier: MIT

Warning was generated by the info-license-url rule.
```

**Comment by jeremyfiel** [comment]
if you configure the rules with the following, it will abide by the spec.   This is a custom, built-in rule from Redocly

```yaml
rules:
  info-license-url: off
```

src: https://github.com/Redocly/redocly-cli/blob/main/docs/rules/info-license-url.md

**Comment by jeremyfiel** [comment]
@SergeAx If you have any other concerns, please raise them here.. Otherwise, please mark this as closed.   thanks so much,

**Comment by SergeAx** [comment]
@jeremyfiel , my point was that the rule is obviously incorrect. Turning it off is sweeping problem under the rug.

**Comment by erayaydin** [comment]
Sorry for bumping @jeremyfiel but, IMO it should be checked `identifier` usage for `license` object. According to OpenAPI 3.1 spec schema[1] it does not require a `URL` field. Organizations can add this requirement with some extra strict rule. There is an issue[2] caused the relevant implementation. Also its make "valid" json schema if there is no `url` field when `identifier` described. Plus, more easy transition from spectral lint to redocly lint.

[1] https://github.com/OAI/OpenAPI-Specification/blob/main/schemas/v3.1/schema.yaml#L108-L112
[2] https://github.com/OAI/OpenAPI-Specification/issues/2975
