### ISSUE TITLE
--prefix-components-with-info-prop repeats prefixes multiple times in $ref's randomly

### ISSUE THREAD

**Issue by okamiraner** [Redocly/redocly-cli#1287]
When join multiple specification with the `join` command and the `--prefix-components-with-info-prop` flag, the resulting specification will contain references with prefixed repeated multiple times based of a random principle like that:

```yaml
... $ref: '#/components/schemas/prefix_prefix_Component'
```

These references cannot be resolved later because components themselves prefixed one time as expected like that:

```yaml
...
        prefix_Component:
...
```

**Comment by jeremyfiel** [comment]
can you provide a minimal example?

**Comment by okamiraner** [comment]
Yes. Joining `redoc.yaml` and `swagger.yaml` gives a duplicate at 428 line in the resulting `openapi.yaml` if run:

```zsh
$ redocly join redoc.yaml swagger.yaml --prefix-components-with-info-prop version --prefix-tags-with-filename
```

**Comment by tatomyr** [comment]
Thanks for reporting! 
@IgorKarpiuk could you check if this is related to https://github.com/Redocly/redocly-cli/pull/1291 and the corresponding issue?

**Comment by IgorKarpiuk** [comment]
@tatomyr It is not related
