### ISSUE TITLE
Make redocly lint exit with non-0 code if there are warnings

### ISSUE THREAD

**Issue by tsauerwein** [Redocly/redocly-cli#1290]
**Is your feature request related to a problem? Please describe.**

In our CI pipeline we are linting with the `recommended` ruleset. For errors, `redocly lint` returns a non-0 exit-code, so that the CI job fails. But we would also like to have `redocly lint` fail, if there are warnings.

**Describe the solution you'd like**

Ideally would be an argument like `--strict` or more exlicit `--fail-on-warnings`. When called with this argument, `redocly lint` would return a non-0 exit-code if there are warnings.

**Describe alternatives you've considered**

It's possible to change the severity of all `warning` rules in the `recommended` ruleset to `error`. But in case the ruleset changes, we would have to adapt our configuration.

**Additional context**

Previous issue is here: https://github.com/Redocly/redocly-cli/issues/747

**Comment by IgorKarpiuk** [comment]
Hi @tsauerwein
Thanks for reporting!

May be it makes sense to add the `--max-warnings` option, just like in ESLint
cc @lornajane @tatomyr

**Comment by lornajane** [comment]
Redocly CLI provides the opportunity to configure each rule to either error or warn (or neither). You already mentioned the alternative: configure the rules and rulesets that work for you - and I would strongly recommend taking this route. I don't think it's helpful to add another option here when this can already be configured and could be confusing to users if it can be set in two places.

**Comment by tsauerwein** [comment]
@lornajane Thanks for taking the time to reply!

Yes, you are right. The alternative of changing the severity of each rule would also do the trick. But it's not very convenient.

I assume the idea of providing a recommended ruleset was to make it as easy as possible for a user to get started. But if I now have to list each (warning) rule of the recommended rule again, it kind of contradicts the idea of making it easier.

In my opinion, the severity of a rule (error/warning) and the way the linter reacts if a rule is broken (exit with 0/non-0), are two different things. Otherwise, why would you even distinguish between errors and warnings? Simply printing out a warning is not very useful considering that linters are used in CI environments, where you have to rely on the exit-code.

Don't get me wrong. I totally get that you don't want to bloat the CLI API. But the fact that a renowned linter like ESLint supports an option like that, shows that there is a need for it.

**Comment by tatomyr** [comment]
> Simply printing out a warning is not very useful considering that linters are used in CI environments

It's just one use case. The linter is also being used in Redocly VS Code extension, and warnings might be helpful there, I believe. 

Anyway, I'm going to add a strict ruleset for the recommended rules soon. What name would you expect it to have? I'm doubting between `recommended-strict` and simply `strict`. Any thoughts?
