### ISSUE TITLE
Lint error: Expected type `Schema` (object) but got `boolean` appears when linting API definition

### ISSUE THREAD

**Issue by ZyzychO** [Redocly/redocly-cli#1296]
**Describe the bug**

Upon linting a valid API Definition, the error message "Expected type `Schema` (object) but got `boolean`" appears

**To Reproduce**

1. Given this `redocly.yaml` file:
[redocly.yaml.zip](https://github.com/Redocly/redocly-cli/files/12884924/redocly.yaml.zip)

2. And this OpenAPI file
[openapi.yaml.zip](https://github.com/Redocly/redocly-cli/files/12884941/openapi.yaml.zip)

3. Run this command: redocly lint openapi.yaml
4. See error: Expected type `Schema` (object) but got `boolean`

**Expected behavior**

In accordance with JSON Schema documentation: 
https://json-schema.org/understanding-json-schema/reference/object#extending, in order to extend closed schemas you can write your schema as in the example below: 

```yaml

components:
  schemas:
    MyObject:
      type: object
      additionalProperties: false
      allOf:
        - $ref: '#/components/schemas/MyObjectBase'
      properties:
        property1: true
        property2: true 
      required:
        - property2
    MyObjectBase:
      type: object
      properties:
        property1:
          type: string
        property2:
          type: string
      required:
        - property1
       
```

However,  it seems Redocly CLI does not cover this use case since the error message occurs:

        
<img width="583" alt="Screenshot 2023-10-12 at 19 40 55" src="https://github.com/Redocly/redocly-cli/assets/106024790/616a7f31-fb7f-4fe0-94c0-2128cbb2227c">

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_25dido)

**Comment by jeremyfiel** [comment]
seems like your indentation is incorrect.  the second allOf schema should be under an array `-` definition

```yaml

components:
  schemas:
    MyObject:
      type: object
      additionalProperties: false
      allOf:
        - $ref: '#/components/schemas/MyObjectBase'
        - properties:
            property1: true
            property2: true 
          required:
            - property2
    MyObjectBase:
      type: object
      properties:
        property1:
          type: string
        property2:
          type: string
      required:
        - property1
       
```

**Comment by jeremyfiel** [comment]
Does this solve your issue? Can this be closed?

**Comment by tatomyr** [comment]
@jeremyfiel I don't think it does. The issue is that the linter doesn't recognise a boolean value of properties. And I don't know if it's better to allow the booleans or use `unevaluatedProperties` (like in [this example](https://json-schema.org/understanding-json-schema/reference/object#unevaluated-properties)) instead of `additionalProperties` + boolean `properties`.

**Comment by lornajane** [comment]
Thanks everyone for the clear explanations. It's a valid bug IMO, although kind of an edge case for a specific way to extend a closed schema, I'm actually not sure I've seen this usage before in an OpenAPI context. For organisations who do control their own schemas, I think enabling `additionalProperties` on the base schema, or refactoring the structure would be a good workaround while we consider how to prioritise adding support for this case.

**Comment by jeremyfiel** [comment]
It depends which version of OAS they are using to determine if this is a bug or not. In JSON Schema draft 7+, it is valid to have a Boolean schema or an object schema but that requires the use of OAS 3.1.x.  if using OAS 3.0.x, Boolean schemas were not allowed and must be an empty schema `property:{}`, in which case this would not be a valid use case and the error is correctly reporting. I figured this usage was intended to be an allOf array of schemas and their indentation was incorrect. I suppose they can also write their schema in the way they've written it, although they need to adjust it with the empty schema.
