### ISSUE TITLE
Have more spec-compliant rulesets

### ISSUE THREAD

**Issue by CidTori** [Redocly/redocly-cli#1331]
**Is your feature request related to a problem? Please describe.**

I wanted to use one of the rulesets but none of them reflect what the OpenAPI spec says, they are all both too strict and too lax.

**Describe the solution you'd like**

I'd like to have a ruleset with the following rules (with their sources):
- spec: error ([obviously](https://redocly.com/docs/cli/rules/spec/#api-design-principles))
- spec-strict-refs: error (it's already explained in the rule itself: ["strict adherence to the specifications"](https://redocly.com/docs/cli/rules/spec-strict-refs/#api-design-principles))
- no-undefined-server-variable: error (same: ["it's an error with the specification"](https://redocly.com/docs/cli/rules/no-undefined-server-variable/#api-design-principles))
- path-declaration-must-exist: error (same: ["This rule is for spec correctness"](https://redocly.com/docs/cli/rules/path-declaration-must-exist/#api-design-principles))
- no-identical-paths: error (["Templated paths with the same hierarchy but different templated names MUST NOT exist as they are identical."](https://spec.openapis.org/oas/latest.html#patterned-fields))
- path-not-include-query: error (["Each template expression in the path MUST correspond to a path parameter"](https://spec.openapis.org/oas/latest.html#path-templating))
- path-parameters-defined: error (["Each template expression in the path MUST correspond to a path parameter"](https://spec.openapis.org/oas/latest.html#path-templating))
- operation-operationId-url-safe: warn (debatable but: ["it is RECOMMENDED to follow common programming naming conventions"](https://spec.openapis.org/oas/latest.html#fixed-fields-7))
- operation-operationId-unique: error (["The id MUST be unique among all operations described in the API."](https://spec.openapis.org/oas/latest.html#fixed-fields-7))
- operation-parameters-unique: error (["The list MUST NOT include duplicated parameters. A unique parameter is defined by a combination of a name and location."](https://spec.openapis.org/oas/latest.html#fixed-fields-7))
- operation-2xx-response: warn (debatable but: ["The Responses Object MUST contain at least one response code, and if only one response code is provided it SHOULD be the response for a successful operation call."](https://spec.openapis.org/oas/latest.html#responses-object))
- no-invalid-parameter-examples: warn (["The example SHOULD match the specified schema and encoding properties if present."](https://spec.openapis.org/oas/latest.html#fixed-fields-9))
- no-invalid-media-type-examples: warn (["The example object SHOULD be in the correct format as specified by the media type."](https://spec.openapis.org/oas/latest.html#fixed-fields-11))
- no-invalid-schema-examples: warn (["It is RECOMMENDED that these values be valid against the associated schema."](https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-validation-00#section-9.5)
- no-example-value-and-externalValue: error (["The value field and externalValue field are mutually exclusive."](https://spec.openapis.org/oas/latest.html#fixed-fields-15))
- no-unresolved-refs: error (debatable but for example: ["The referenced structure MUST be in the form of a Path Item Object."](https://spec.openapis.org/oas/latest.html#fixed-fields-6))
- spec-components-invalid-map-name: error (["All the fixed fields declared above are objects that MUST use keys that match the regular expression: ^[a-zA-Z0-9\.\-_]+$."](https://spec.openapis.org/oas/latest.html#fixed-fields-5))

(As you can see, I used `error` for REQUIRED rules in the spec, and `warn` for RECOMMENDED rules)

It would be great to also have a ruleset (extending the previous one) with less-opinionated, "best practices" rules:
- no-server-example.com: warn (useless, so certainly a copy-paste error)
- no-server-trailing-slash: warn (safer and with no downside)
- no-ambiguous-paths: warn (safer but not always easy to see, so it's quite useful to lint them)
- no-path-trailing-slash: warn (safer and with no downside)
- operation-operationId: warn (as the rule itself says: "This rule is unopinionated.")
- no-enum-type-mismatch: warn (as the rule itself says: "Lack of compliance is most likely the result of a typo.")
- no-unused-components: warn (more secure, and useful to lint them to find and remove them if possible)

**Describe alternatives you've considered**

I defined my own set of rules, but copy-pasting it everywhere is error prone, and I just think it would benefit everyone to be able to use it.

**Comment by tatomyr** [comment]
> copy-pasting it everywhere is error prone

Have you considered [extending](https://redocly.com/docs/cli/configuration/extends/) your configuration files from a shared (probably even public) ruleset instead of copy-pasting?

**Comment by lornajane** [comment]
Thank you very much for sharing this! There's a lot to think about here, and I appreciate the input and suggestions. Did you already see that we recently set up a community cookbook where you can share your ruleset? (no pressure at all, just if you want to because it sounds like you have expertise to share!) It's here: https://github.com/Redocly/redocly-cli-cookbook

**Comment by CidTori** [comment]
> > copy-pasting it everywhere is error prone
> 
> Have you considered [extending](https://redocly.com/docs/cli/configuration/extends/) your configuration files from a single shared (probably even public) ruleset instead of copy-pasting?

I didn't, I'll try using that, thanks 🙂

But it means I'll need something to expose publicly that single ruleset (or both, but the first one is more important), so I'd prefer if it was built-in (but that is up to you 🙂)

**Comment by CidTori** [comment]
> Thank you very much for sharing this! There's a lot to think about here, and I appreciate the input and suggestions. Did you already see that we recently set up a community cookbook where you can share your ruleset? (no pressure at all, just if you want to because it sounds like you have expertise to share!) It's here: https://github.com/Redocly/redocly-cli-cookbook

Thanks, I'll share it as soon as possible 🙂

**Comment by CidTori** [comment]
From a more "marketing" point of view, I started using your plugin because it was the VSCode plugin that was the closest (some rules make it even better) to IntelliJ Idea Ultimate bundled OpenAPI plugin, which stick quite close to the spec and does not need any additional configuration file for that purpose.

But when I installed your plugin, the default ruleset was quite far from the spec, and I had to add a configuration file to make it useable (useful linting without too much noise) on existing, spec compliant swaggers.

So I think a default ruleset strictly following the spec would benefit Redocly by making it easier to use out-of-the-box.

**Comment by tatomyr** [comment]
> But it means I'll need something to expose publicly

This 'something' is nothing short of a yaml file, so any static server would do the work. Then you should be able to reference it, e.g. via a URL. 

> I'd prefer if it was built-in, or even better if it was the default

I don't see we replace the default recommended ruleset with yours in the nearest future (however good it is 🙂), but adding it as a built-in most likely will depend on its popularity.

**Comment by CidTori** [comment]
Of course 🙂

**Comment by adamaltman** [comment]
I just saw this issue. Very thoughtfully written @CidTori ! 👏 

I think there is still more do to to make it more strict. I just opened this issue (which I thought I had reported before).

https://github.com/Redocly/redocly-cli/issues/1347

**Comment by lornajane** [comment]
We've got two excellent rulesets added to the [Redocly CLI cookbook](https://github.com/Redocly/redocly-cli-cookbook), thank you @CidTori !  We'll keep an eye on them over there, and consider what to do next time we review our built-in rulesets. Since @adamaltman opened #1347 separately, I'm going to close this issue now.
