### ISSUE TITLE
JSON Schema's `required` property could contain an unknown property

### ISSUE THREAD

**Issue by tatomyr** [Redocly/redocly-cli#1333]
**Is your feature request related to a problem? Please describe.**

Consider the following schema:

```yaml
openapi: 3.1.0
components:
  schemas:
    MySchema:
      properties:
        foo: 
          type: string
      required:
      - bar # <-- there's no such a property declared
```

There's no such a property like `bar` defined, yet it is required in the schema. Even technically it isn't wrong as there's no `additionalProperties: false` clause, I don't think there's too much sense to require a property that is not declared in the schema. Most likely it'd be a typo, I believe. Currently Redocly linter doesn't catch this.

**Describe the solution you'd like**

A new rule to check if the `required` list contains only already declared properties of the schema. 

**Describe alternatives you've considered**

Writing a custom rule. Always an option instead of writing a built-in one.
There's no possibility to write this as a configurable rule, unfortunately.

**Comment by tatomyr** [comment]
@adamaltman you mean [this one](https://github.com/Redocly/redocly-cli/issues/477)? Somehow it slipped my mind that there already was one.

**Comment by lornajane** [comment]
How about a rule named `missing-required-schema-properties` ? (Naming things might be the most difficult part of this!)
