### ISSUE TITLE
OAS 3.1 : summary should not be mentionned as a warning , display and rendering rendered as x-summary 

### ISSUE THREAD

**Issue by LasneF** [Redocly/redocly-cli#1376]
**Describe the bug**

Redoc is supposed to fully supprt OAS 3.1 
the fied summary is standard and should be fully supported not reporting a warning 
it should works as same as x-summary   

**To Reproduce**
add a summary on a responses as below 

![image](https://github.com/Redocly/redocly-cli/assets/12461661/b506297a-bfa1-473a-a34e-ec56c9f4bbac)

    401-Unauthorized:
      summary: Unauthorized
      description: Unauthorized - Authentication is required.

**Expected behavior**

No warning on linter , same representation for summary and x-summary 

**Redocly Version(s)**

Redocly 1.6.0

**Comment by tatomyr** [comment]
Hi @LasneF! According to the spec, there's no such filed in the Response Object as summary: https://spec.openapis.org/oas/v3.1.0#fixed-fields-14. Am I missing something?

**Comment by LasneF** [comment]
@tatomyr , i apologize sorry for the noise , and thanks for the clarification
