### ISSUE TITLE
Move API client to cli package and handle proxy

### ISSUE THREAD

**Issue by IgorKarpiuk** [Redocly/redocly-cli#1404]
**Task**

Investigate possibility to move `core/src/redocly` directory from `core` to `cli` package to decrease bundle size.  And use `fetchWithTimeout` where it is necessary for api client. 

For `fetchWithTimeout`  function add ability to work behind proxy.

**References**

https://github.com/Redocly/redocly-cli/issues/529
https://github.com/Redocly/redocly-cli/pull/1321#discussion_r1464508929

**Comment by tatomyr** [comment]
Tangentially related: https://github.com/Redocly/redocly-cli/pull/1423
