### ISSUE TITLE
lint command doesn't support `"const"` in schema

### ISSUE THREAD

**Issue by sbdchd** [Redocly/redocly-cli#1411]
**Describe the bug**

lint command spec rule doesn't support the usage of the `"const"` field in the schema from the open api v3

**To Reproduce**

1. Given this `redocly.yaml` file
no config setup
3. And this OpenAPI file(s)

```json
{
  "openapi": "3.0.0",
  "info": {
    "title": "API",
    "version": "1.0.0"
  },
  "paths": {
    "/api/v1/foo": {
      "post": {
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "created": {
                      "format": "date-time",
                      "type": "string"
                    },
                    "modified": {
                      "format": "date-time",
                      "type": "string"
                    },
                    "type": {
                      "const": "note",
                      "default": "note"
                    }
                  },
                  "type": "object"
                }
              }
            }
          }
        }
      }
    }
  }
}
```

4. Run this command with these arguments... `redocly ...`

```
npx @redocly/cli lint example-openapi.json
```

6. See error

**Expected behavior**

```

[2] example-openapi.json:26:23 at #/paths/~1api~1v1~1foo/post/responses/200/content/application~1json/schema/properties/type/const

Property `const` is not expected here.

Did you mean: not ?

24 | },
25 | "type": {
26 |   "const": "note",
27 |   "default": "note"
28 | }

Error was generated by the spec rule.
```

**Logs**

**OpenAPI description**

**Redocly Version(s)**

1.8.0

**`Node.js` Version(s)**

v16.16.0

**Additional context**

rel: https://github.com/OAI/OpenAPI-Specification/issues/1313

**Comment by lornajane** [comment]
Thanks @sbdchd , this is a good question - but I don't think it's a bug.

To represent what you're looking for in OpenAPI 3.0 (it changed in 3.1), the best approach would be to use a type string and an enum with a single value, like this:

```json
                    "type": {
                      "type": "string",
                      "enum": ["note"]
                    }
```

I think this will give the behaviour you expect, please give it a try and let us know. Your original syntax isn't supported by OpenAPI 3.0 which is why the linter picks it up.

**Comment by sbdchd** [comment]
Oh good catch, it's working great now that I've updated the version number. Thank you!!
