### ISSUE TITLE
Path containing # breaks path resolution

### ISSUE THREAD

**Issue by avanbremen** [Redocly/redocly-cli#1441]
**Describe the bug**

When the `$ref` contains `#` I receive: `Can't resolve $ref: ENOENT: no such file or directory`.

Similar to issue #1392.

Most likely due to [change](https://github.com/Redocly/redocly-cli/compare/%40redocly/cli%401.8.2...%40redocly/cli%401.9.0#diff-25c0338c90db3454ba7548187ad0db4e1e288ffca3c1d6ef65f45a442e728074) in `ref-utils.ts`.

Tested with release [@redocly/cli@1.9.0](https://github.com/Redocly/redocly-cli/releases/tag/%40redocly%2Fcli%401.9.0).

**To Reproduce**

For example:

`openapi.yml`

```yaml
openapi: 3.1.0

info:
  title: My API
  version: 1.0.0
  description:
    $ref: './info#description.md'
```

`info#description.md`

```markdown
# Description

Redocly is awesome.
```

**Expected behavior**

Success.

**Logs**

```
Can't resolve $ref: ENOENT: no such file or directory '/home/runner/work/openapi-specification/openapi-specification/src/v1/info'
```

**OpenAPI description**

**Redocly Version(s)**

`1.9.0`

**Additional context**

Similar to issue #1392.

GitHub Actions runner version: `2.313.0`.

**Comment by jaredLunde** [comment]
This downstream issue is also related to the change to `ref-utils.ts`
https://github.com/drwpow/openapi-typescript/issues/1542#issuecomment-1947507415

**Comment by tatomyr** [comment]
Hey guys. Prepared a fix. Feel free to leave your comments: https://github.com/Redocly/redocly-cli/pull/1445.

**Comment by tatomyr** [comment]
@avanbremen, @jaredLunde could you confirm the issue got resolved in v1.9.1?

**Comment by jaredLunde** [comment]
@tatomyr this fixed the issue for me 😄 thank you!

**Comment by avanbremen** [comment]
@tatomyr tested with latest ([1.10.1](https://github.com/Redocly/redocly-cli/releases/tag/%40redocly%2Fcli%401.10.1)), the issue is now solved. Thanks!
