### ISSUE TITLE
Improves to lint output

### ISSUE THREAD

**Issue by DmitryAnansky** [Redocly/redocly-cli#1450]
**Is your feature request related to a problem? Please describe.**

By using `redocly lint openapi.yaml` to debug some errors in a big openAPI document I found it complicated to notice the actual errors behind a bunch of warnings.

<img width="431" alt="Screenshot 2024-02-26 at 12 08 11" src="https://github.com/Redocly/redocly-cli/assets/2563120/3e3486e5-9eb7-4b29-86d7-ae204b99348e">

Warnings are printed after errors in console - so in some cases user can't see errors as consoles have some limitations in display.
There is a workaround to disable some warning rules, but it requires some extra actions, when you just want to fix critical errors.

**Describe the solution you'd like**

Suggestions:
 to switch the order of display, so that `errors` are shown after `warnings`. This will allow to see critical issues in the documents.

**Describe alternatives you've considered**

Add some `disable wanrings` flag to display only critical issues.

**Additional context**

**Comment by lornajane** [comment]
If you have to pick one approach that would be probably-fine for everyone, the current way of showing errors and then warnings is the correct one. We advise all users to configure their rulesets according to the level of validation that makes sense for their project, let us know if you need help with the rulesets, but I'll close this issue as this change isn't planned.
