### ISSUE TITLE
Validation error: type required when nullable is true

### ISSUE THREAD

**Issue by pantsmann** [Redocly/redocly-cli#1480]
**What happened?**

A property has nullable = true and allOf set to $ref and the validation says there is an error because type is missing.
```
...
      "properties":{
           "somefield": {
                  "allOf": [
                        { 
                            "$ref": "#/components/schemas/SomeType"
                        }
                   ]
                   "nullable": true
...
```

**What should have happened instead?**

"allOf", in this case, takes the place of "type" so there should be no error. If this is not the case then what type would not conflict with the $ref?

I recognize that the 3.0.3 spec only mentions "type" being needed if "nullable" is true, but the construction above is valid and is the standard way of including a ref. At least that is my understanding.

**Minimal reproducible OpenAPI snippet**

**Screenshots**

**Additional context**

extension version v0.4.3
OpenAPI version 3.0.3

**Comment by adamaltman** [comment]
This is not valid. 

![image](https://github.com/Redocly/redocly-cli/assets/1161871/0dcf313e-5811-4c1e-824c-0554d645c6c1)

This is not valid:
```
type:
  nullable: true
  allOf:
    $ref: '#/components/schemas/SomeType'
```
This is valid:
```
type:
  nullable: true
  type: # (replace with the same type as SomeType such as string, object, etc.
  allOf:
    $ref: '#/components/schemas/SomeType'
```
