### ISSUE TITLE
`@redocly/config` is missing a license

### ISSUE THREAD

**Issue by CiaranMn** [Redocly/redocly-cli#1487]
**Is your feature request related to a problem? Please describe.**

New internal dependency `@redocly/config` doesn't have a license set via `package.json` or a `LICENSE(.md)` file.

**Describe the solution you'd like**

An explicit license is set for the package for the avoidance of doubt.

**Additional context**

This was flagged by dependency license scanning.

**Comment by tatomyr** [comment]
Thanks for letting us know!
