### ISSUE TITLE
Review and update the quickstart guide

### ISSUE THREAD

**Issue by lornajane** [Redocly/redocly-cli#1517]
The [Redocly CLI Quickstart guide](https://redocly.com/docs/cli/quickstart) has not been updated in quite some time.

Could we please:
 - [ ] check the existing instructions still work
 - [ ] improve the copy on this page, including something about why each task is useful
 - [ ] add some additional common first tasks, such as defining a ruleset or bundling a file

**Comment by techstacksavvy** [comment]
Hi @lornajane!

Has the work for this issue been completed?

**Comment by lornajane** [comment]
@techstacksavvy Not yet! I'd be happy to review a pull request.

**Comment by techstacksavvy** [comment]
Hi @lornajane, I've submitted a PR for this issue.
