### ISSUE TITLE
Incorrect command to preview local docs changes in contributing.md 

### ISSUE THREAD

**Issue by dianacheung** [Redocly/redocly-cli#1532]
**Describe the bug**

In the contributing guide (contributing.md), it currently states:

> To preview your changes locally, run this command from the docs/ folder:
> `https://redocly.com/docs/cli/`

The above command is incorrect and will result in an error stating that it is not a valid command.

**To Reproduce**

1. Navigate to the docs/ folder
2. Run `https://redocly.com/docs/cli/`
3. See error

**Expected behavior**

The correct command to run is: `redocly preview`
Running the above command will start a local preview server for the docs/ folder. By default, see the docs preview at `http://localhost:4000` or `http://127.0.0.1:4000`.

Note: Make sure redocly is already installed. Include link to installation instructions https://redocly.com/docs/cli/installation/.

**Comment by dianacheung** [comment]
I can work on this issue.

**Comment by dianacheung** [comment]
Hi @lornajane, PR https://github.com/Redocly/redocly-cli/pull/1533 awaiting review approval. Thanks.

**Comment by tatomyr** [comment]
I believe this on is resolved by https://github.com/Redocly/redocly-cli/pull/1533.

**Comment by tatomyr** [comment]
I believe this on is resolved by https://github.com/Redocly/redocly-cli/pull/1533.
