### ISSUE TITLE
redocly lint format html or markdown

### ISSUE THREAD

**Issue by marianobntz** [Redocly/redocly-cli#1539]
**Is your feature request related to a problem? Please describe.**

I am using redocly to generate the lint report to see warnings in an azure devops pipeline. I would like to show the lint report inside the pipeline results but I am having trouble finding a way to do it.

Any current format (1.11.0) is not suitable to upload directly so I would need to transform the report to another format and then upload.

**Describe the solution you'd like**

A new format for lint for markdown or html would greatly help my task. Thanks,

**Describe alternatives you've considered**

I am evaluating which format is more suitable for transformation but I could not find anything useful yet. Doing json to html convertion would be really difficult.

**Additional context**

**Comment by tatomyr** [comment]
Hi @marianobntz! How would you expect the results to be formatted in the markdown format? 
I'm not sure, but maybe using the `stats` [command](https://redocly.com/docs/cli/commands/stats/#markdown) with the `--format=markdown` option could be a workaround for your case?

**Comment by marianobntz** [comment]
Will try it but I need the actual warnings and errors just like the codeframe format. Will let you know soon.

Thanks

**Comment by marianobntz** [comment]
Just FYI... I made a powershell script to parse the redocly codeframe output and show it in Azure Devops pipeline as warnings and errors in the pipeline run.

Not sure how to add it to the cookbook or not... but I can try if you think it is worth it 😄

**Comment by lornajane** [comment]
That's pretty cool. Did you see that we also added a markdown output format to the lint command? It's in #1559  - merged but not released yet.

**Comment by marianobntz** [comment]
yes yes, saw the PR, it would have helped with my parsing 😃 but now I like having the errors and warnings in the pipeline ... that way my analysts can see the problems pretty easily... 

I will take a look at the markdown output when it is released! THANKS!

**Comment by lornajane** [comment]
It's in 1.13.0 onwards, so I'll close this issue since I don't think there's anything more for us to do here (but still happy to hear feedback!)
