### ISSUE TITLE
dependentRequired is valid json schema but does not pass linting and prevents component from being available in UI.

### ISSUE THREAD

**Issue by jmacelroy** [Redocly/redocly-cli#1558]
**Describe the bug**

Property `dependentRequired` is not expected here is reported when running the linter. I would expect for an OpenAPI 3.1.0 spec for this to lint and be reflected in the UI generated as it seems to be part of the supported JSON Schema dialect.T

**To Reproduce**

1. Given this `redocly.yaml` file
```
# See https://redocly.com/docs/cli/configuration/ for more information.
extends:
  - recommended 
rules:
  no-unused-components: error
  no-server-example.com: off
  no-empty-servers: off
  security-defined: off
  info-license: off
  operation-4xx-response: off # https://phab.easypo.net/T72078 turn this back on when 4xx are added.
theme:
  openapi:
    htmlTemplate: ./docs/index.html
    theme:
      colors:
        primary:
          main: "#32329f"
    generateCodeSamples:
      languages:  # Array of language config objects; indicates in which languages to generate code samples.
        - lang: curl
```

2. And this OpenAPI file(s) which is using schema example from https://json-schema.org/understanding-json-schema/reference/conditionals#dependentRequired

```
openapi: 3.1.0
info:
  version: 1.0.0
  title: This is only a test.
  description: testing
paths:
  '/test':
    post:
      summary: test use of dependentRequired 
      operationId: test
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  credit_card:
                    type: number
                  billing_address:
                    type: string
                required:
                - name
                dependentRequired:
                  credit_card:
                  - billing_address

```

3. Run this command with these arguments... `redocly ...`
`redocly lint openapi.yaml

6. See error
```
❯ redocly lint openapi.yaml
(node:45032) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
validating openapi.yaml...
[1] openapi.yaml:27:17 at #/paths/~1test/post/responses/200/content/application~1json/schema/dependentRequired

Property `dependentRequired` is not expected here.

25 | required:
26 | - name
27 | dependentRequired:
28 |   credit_card:
29 |   - billing_address

Error was generated by the spec rule.


openapi.yaml: validated in 7ms

❌ Validation failed with 1 error.
run `redocly lint --generate-ignore-file` to add all problems to the ignore file.
```

**Expected behavior**

The lint should pass.

**Logs**

n/a

**OpenAPI description**

Included above.

**Redocly Version(s)**

1.12.2

**`Node.js` Version(s)**

21.6.2

**Additional context**

I have tried to double check that it's not just a formatting error but this looks to be correct according the the json schema doc and is not a linting error when running spectral

**Comment by tatomyr** [comment]
Hey @jmacelroy! Thanks for reporting!

**Comment by tatomyr** [comment]
BTW, what do you mean by '...prevents component from being available in UI'? Is it just linter failing and not passing to the next step or you'd expect the `dependentRequired` key to somehow be rendered on the UI? If the latter, you should probably open an issue in the [Redoc repository](https://github.com/Redocly/redocly-cli/issues/1558).

**Comment by jeremyfiel** [comment]
@tatomyr  the type is not defined here.. https://github.com/Redocly/redocly-cli/blob/main/packages/core/src/types/oas3_1.ts#L90

should probably be defined with something similar to `NamedSchemas` 

```js
export const Oas3_1Types: Record<Oas3_1NodeType, NodeType> = {
...
dependentRequired: 'NamedDependents'
};

export const Oas3_1Types: Record<Oas3_1NodeType, NodeType> = {
 ...
  NamedDependents: mapOf( { type: 'string' }, listOf({ type: 'string' }))  <<< How do you define the value separately from the key? 

};
```

>**dependentRequired : Object<String, Array<String>>**
Validation succeeds if, for each name that appears in both the instance and as a name within this keyword’s value, every item in the corresponding array is also the name of a property in the instance.

_src: https://www.learnjsonschema.com/2020-12/validation/dependentrequired/_


I'm just not clear on how you define that because I don't see any similar types for the current list.  If this type definition is correct, I can make the PR for you.  Just let me know how to define the type. 

---

repro example

```json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "name": { "type": "string" },
    "age": { "type": "integer" },
    "license": { "type": "string" }
  },
  "dependentRequired": {
    "license": [ "age" ]
  }
}
```

```json
{
  "name": "John",
  "age": 25,
  "license": "XYZ123"
}
```

**Comment by tatomyr** [comment]
@jeremyfiel you're correct. And there is one more issue that I think is related to missing the type there: https://github.com/Redocly/redocly-cli/issues/1598.
