### ISSUE TITLE
Configure object order for redocly bundle command

### ISSUE THREAD

**Issue by andiahlm** [Redocly/redocly-cli#1588]
**Is your feature request related to a problem? Please describe.**

The order of the root objects in our OAS3 specification is changed during 'redocly bundle' command.
This is of a certain importance to as since it is required by our clients specification governance.
I could not find examples where the order of objects can be customized.
Is this in general possible?
What is the reasoning for the default order redocly proposes?

**Describe the solution you'd like**

A nice feature would be if we could configure (in the config file) the order of objects according to some rules (i.e. explicit listing, alphabetically etc) which is applied during the 'redocly bundle' command.
This behavior would also be nice on deeper nodes such as the parameters within the components.

**Additional context**

If this feature is already available and my ignorance has not found it yet, I apologize for the issue.

Many thanks in advance
Andreas

**Comment by tatomyr** [comment]
Hi @andiahlm. I don't think the `bundle` command should do reordering. You can easily achieve what you want with a tiny script like this:

```js
/* reorder.js */

const fs = require("fs")
const {parseYaml, stringifyYaml} = require("@redocly/openapi-core")

const reorder = root => {
  const {components, openapi, ...rest} = root
  return {
    // Here you can put the properties in the order you want
    components,
    ...rest,
    openapi,
  }
}

const fileName = process.argv[2]
const content = fs.readFileSync(fileName, "utf8")
const reordered = reorder(parseYaml(content))
process.stdout.write(stringifyYaml(reordered))
```

Then you can bundle the description and transform it with something like the following: `node reorder.js <path-to-the-bundled-file.yaml>`.

Please let me know if that hellps.

**Comment by andiahlm** [comment]
Hi @tatomyr , this is of great help - many thanks for the quick response and the detailed suggested script!
