### ISSUE TITLE
Example validation is not done against the schema 

### ISSUE THREAD

**Issue by LasneF** [Redocly/redocly-cli#1616]
**Describe the bug**

redocly is not able to detect that the sample provided does not respect the schema ( given the schema is not perfect) 

here the issue is that the oneOf is wrong , as not discriminant enought 
when leveraging a json schema validator the sample is set as invalid 
I would expect that Redocly validate each sample toward the schema  (at object or endpoint level) 

**To Reproduce**

given this API specification 
[sample.json](https://github.com/user-attachments/files/16142866/sample.json)

redocly reply 'Woohoo! Your API description is valid. 🎉" 

**Expected behavior**

i would expect that the example is validated against the schema , and so here that there would be a warning , or even an error mentionning that the sample is wrong , please correct sample our double check your schema defintiion 

**version**
redocly --version
1.17.1

**Comment by jeremyfiel** [comment]
this is invalid JSON Schema because the `oneOf` doesn't have `unevaluatedProperties: false` defined.  thus, both schemas are valid.

Try this. 

```json
 "components": {
        "schemas": {
            "Pet": {
                "type": "object",
                "oneOf" : [
                    {
                        "properties" : {
                            "pim" : {"type":  "string"}
                        }, "unevaluatedProperties": false
                    },
                    {
                        "properties" : {
                            "pam" : {"type":  "string"}
                        }, "unevaluatedProperties": false
                    }
                ],
                "example" : 
                { 
                    "pam" : "nop"
                }
            }
        }
    }
```
---  

based on your other request to require `type` keyword (#1614), this schema would also flag a warning because it does not consider the `type: object` defined as a sibling to `oneOf`.  each `oneOf` sub-schema is considered a separate schema.

**Comment by jeremyfiel** [comment]
Btw, the rules do work correctly for this example. 

```yaml
rules:
  no-invalid-schema-examples: warn
```

--- 

This gives me a warning f
![image](https://github.com/Redocly/redocly-cli/assets/32110157/174c7905-f09c-43f0-b72b-e771c4d004a3)
or invalid example

**Comment by jeremyfiel** [comment]
if you're using `extends: [recommended]` ruleset.  this particular rule is turned off.  you need to set it manually in your `rules`

https://github.com/Redocly/redocly-cli/blob/4c3d8cf84f0c831777660f8d328c15fb71163f14/packages/core/src/config/recommended.ts#L35C6-L35C41

**Comment by LasneF** [comment]
@jeremyfiel thanks a lot for the investigation , I apologize for the disturb 

i did not realize that there was some rules off when doing redocly lint , 

you may consider to enable it by default in recommended , the rational is that example can be use in various use case such as generate postman , or bruno collection where they would input wrong statement , or when doing a static mock 

having sample in line with the schema looks usefull in those scenario . 

Thanks again for your great tool , i let you closing the ticket or use it to update if you beleive it should the level

**Comment by jeremyfiel** [comment]
This rule is off because it's recommended to use media-type `examples` as mentioned by @tatomyr . 

You can update your schema like this: 


```json
{
    "openapi": "3.1.0",
    "info": {
        "title": "this is the title",
        "description": "this is the description",
        "license": {
            "name": "nothing",
            "url": "nowhere"
        },
        "version": "1.0"
    },
    "security": [],
    "servers": [
        {
            "url": "https://api.server.test/v1"
        }
    ],
    "paths": {
        "/test": {
            "post": {
                "summary": "Pet",
                "operationId": "getTest",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Pet"
                            },
                            "examples": {
                                "pet_request": {
                                    "$ref": "#/components/examples/pet"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "testOK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Pet"
                                },
                                "examples": {
                                    "pet_response": {
                                        "$ref": "#/components/examples/pet"
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "input issue"
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "Pet": {
                "type": "object",
                "oneOf": [
                    {
                        "type": "object",
                        "properties": {
                            "pim": {
                                "type": "string"
                            }
                        },
                        "unevaluatedProperties": false
                    },
                    {
                        "type": "object",
                        "properties": {
                            "pam": {
                                "type": "string"
                            }
                        },
                        "unevaluatedProperties": false
                    }
                ]
            }
        },
        "examples": {
            "pet": {
                "summary": "a sample pet object",
                "value": {
                    "pam": "nop"
                }
            }
        }
    }
}

```

**Comment by tatomyr** [comment]
Thanks for the kind words, @LasneF!

I'll close the issue since it's up to you which rule you want to use 🙂. You can explore the rules and create and share your own ✨best-in-the-world✨ ruleset that can then be reused in any other project simply by using the extends option.

@jeremyfiel thanks for chiming in and for the detailed explanation!
