### ISSUE TITLE
Remove `node-fetch` package and use Node.js 18 native`fetch`

### ISSUE THREAD

**Issue by mauriciabad** [Redocly/redocly-cli#1659]
In another project using Redocly, displays an error on console due to this package. More details: https://github.com/OpenAPI-Qraft/openapi-qraft/issues/117#issuecomment-2271081645

It is an error caused by `node-fetch` package that hasn't been updated for a year and it uses a deprecated dependency.

But there's no need to have the node-fetch dependency because `fetch` is natively available since Node.js@18 and it is the same as `node-fetch`.

Just removing `node-fetch` and updating the node version to 18 would fix the issue.

**Comment by mauriciabad** [comment]
I tried to open a PR implementing this, and it is not as straightfowrard as it seems.

In the `uploadFileToS3` function a stream is used as body, which is not supported in the native fetch. 

A possible solution would be to use another library like `undici` or `axios` for this specific function and use native fetch for the rest of functions.

**Comment by tatomyr** [comment]
Hi @mauriciabad. Currently, Redocly CLI supports Node versions prior to 18, so I wouldn't remove the node-fetch package just to maintain backward compatibility. However, we might reconsider this in the future. Thanks for the suggestion.
