### ISSUE TITLE
Question regarding skipping preprocessors and decorators during bundle operation

### ISSUE THREAD

**Issue by andiahlm** [Redocly/redocly-cli#1665]
Dear Redocly team,

We experience some issues with side effects during the bundling process with unwanted side effects, for example:
- Line breaks in multiline descriptions are being removed
- Single-quotes on pattern property are being removed
We understand that this may be best-practices however our internal guidelines do not allow us to to change these conventions yet.

My question:
Is there a documented list of default preprocessors and decorators that are applied during a bundle operation and secondly is there a possibility to skip selected processors?

Many thanks in advance
Andreas

**Comment by tatomyr** [comment]
Redocly CLI does not run any default decorators. Are you bundling yaml files? If yes, it's most likely not a side effect of a decorator or preprocessor, but a side effect of the bundling itself. The `bundle` command takes your yaml files, transforms them into json to resolve the refs, and them converts into yaml again. Could you show an example of the wrong and expected output?

**Comment by andiahlm** [comment]
Many thanks for the quick response. Your assumption is correct, that we are bundling YAML files. We are using redocly v1.19.0. Here is an example to reproduce the behaviour:

API.yaml:

```yaml
openapi: 3.1.0
info:
  version: v1
  title: Sample OAS
  description: |
    First line description.
    Second line description.
paths:
  /models:
    get:
      summary: This is a summary
      description: >
        First Line description.
        Second line description.
      responses:
        '200':
          description: Returns a list of all models.
          content:
            application/json:
              schema:
                $ref: 'Model.yaml'
```

Model.yaml:

```yaml
title: Model
type: object
description: Model entity.
properties:
  name:
    type: string
    description: |
      First line of the description.
      Second line of the description.
  currency:
    type: string
    pattern: '^[A-Z]{3}$'
    example: EUR
    description: The ISO3 code of the currency.
```

After executing

```bash
redocly bundle API.yaml --ext yaml --output API-bundled.yaml
```

the resulting bundled API looks like this:

```yaml
openapi: 3.1.0
info:
  version: v1
  title: Sample OAS
  description: |
    First line description.
    Second line description.
paths:
  /models:
    get:
      summary: This is a summary
      description: |
        First Line description. Second line description.
      responses:
        '200':
          description: Returns a list of all models.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Model'
components:
  schemas:
    Model:
      title: Model
      type: object
      description: Model entity.
      properties:
        name:
          type: string
          description: |
            First line of the description.
            Second line of the description.
        currency:
          type: string
          pattern: ^[A-Z]{3}$
          example: EUR
          description: The ISO3 code of the currency.

```

Notice the change in line break in the path description and the removal of single quotes on the pattern of the 'currency' property.

Many thanks in advance for looking into this!
Best regards
Andreas

**Comment by tatomyr** [comment]
Thanks for the example! I believe it's similar to [this issue](https://github.com/Redocly/redocly-cli/issues/1500). 
While there's no way to preserve the original formatting, it should be possible to apply the desired formatting to the output YAML file after the bundle step using a separate tool. 
Anyway, the output is correct, so I'm closing the issue. Please let us know if you need any further assistance, and keep me updated here if you manage to resolve your problem.
