### ISSUE TITLE
for 'redocly lint', how to suppress the the 'new version available' check/output?

### ISSUE THREAD

**Issue by etnt** [Redocly/redocly-cli#1680]
Hi,
The 'redocly lint' command prints out a blurb about a new version being available.
It does so with some funny chars (color codes?) that screw up our expect test framework.
So my questions are:

1. How can I suppress this 'new version' check?
2. If (1) is not possible, how can I suppress the output?

Thanks, T.

**Comment by tatomyr** [comment]
Hi @etnt, here's the workaround: https://github.com/Redocly/redocly-cli/issues/1639#issuecomment-2239085770

I'm closing this ticket as it's a duplicate of https://github.com/Redocly/redocly-cli/issues/1639

**Comment by etnt** [comment]
Excellent! Thanks for the super quick reply :-)
