### ISSUE TITLE
Add documentation for Arazzo rules and linting

### ISSUE THREAD

**Issue by DmitryAnansky** [Redocly/redocly-cli#1691]
**Describe the bug**

New rules for `AsyncAPI` and `Arazzo` are not described in config sections like 
https://redocly.com/docs/cli/rules/recommended.

We need to update it for all config pages: all, recommended, minimal, strict-recommended.

Also, lest review `severity` levels in predefined rulesets. Check with @tatomyr and @lornajane

**Comment by lornajane** [comment]
Also to include with these docs changes:

- a new top-level configuration entry `arazzoRules`
- we'll need additional ruleset documentation for each rule that was added, and for the arazzo version of the minimal/recommended/etc rulesets

**Comment by JLekawa** [comment]
Blocked until #[1800](https://github.com/Redocly/redocly-cli/pull/1800) merges.
