### ISSUE TITLE
How to ignore a JSONSchema property in linting?

### ISSUE THREAD

**Issue by goldingdamien** [Redocly/redocly-cli#1693]
I can see references to allowing all additionalProperties: https://github.com/Redocly/redocly-cli/issues/477
However, I would like to allow just a single property. Is this possible? How should this be done?
※ The property is errorMessage used in ajv, etc.
Regards.

**Comment by goldingdamien** [comment]
@tatomyr 

Yes sure, the project I am working on has the property "errorMessage" added to JSONSchema.
I am using "redocly lint" to lint the JSONSchema file, but an error is occurring that is complaining about "errorMessage" not being valid. "errorMessage" does not seem to be a valid JSONSchema property so it makes sense that an error occurs. However, if possible, I would like to ignore just this property in "redocly lint" so I get no errors.

Regards.

**Comment by tatomyr** [comment]
There are a couple of ways to achieve that. A minimal example, the OAS version, and other details would greatly help me recommend the best one for your case.

**Comment by goldingdamien** [comment]
@tatomyr 
It is company code so I can not share any existing code. The following should convey the issue:

"openapi": "3.0.3"

JSONSchema parts such as in requestBody:
```
{
  "type": "object",
  "required": ["my-property"],
  "properties": {
    "my-property": {
      "errorMessage": {
        "pattern": "this is a string"
      }
    }
  }
}
```
// Property errorMessage is not allowed.

**Comment by tatomyr** [comment]
Thanks for the example. Yes, that property is not allowed by the [3.0.3 specification](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#schema-object). If you are absolutely sure it's not an error, you have three options. 
First, you can use a [specification extension](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#specification-extensions) instead (rename to `x-errorMessage`).
Second, create ignore file for this specific error: https://redocly.com/docs/cli/commands/lint#generate-ignore-file.
And the last option is to extend the `Schema` type via a custom plugin: https://redocly.com/docs/cli/custom-plugins/extended-types#type-extensions-in-plugins.

Let me know if that helps.

**Comment by goldingdamien** [comment]
Do "specification extension"s work in JSONSchema? (Seems OpenAPI specific.)
The ignore file looks like it would be a good solution, but how is it possible to ignore a specific property name (Not rule)? It must work for all occurrences of the property.
I assume Schema of https://redocly.com/docs/openapi-visual-reference/openapi-node-types can be used to add the property. Looks like it might a bit more work and understanding getting working, so I will consider as a last resort.

The simplest way would be best.
If ignore via schema property is possible, the ignore file seems best.
If x-errorMessage is possible in JSONSchema, I will consider that next.
Otherwise, I'll consider either the plugin or getting the schema completely changed.

**Comment by tatomyr** [comment]
> Do "specification extension"s work in JSONSchema? (Seems OpenAPI specific.)

In OAS 3.0.3 the schema objects are defined as an extended subset of the [JSON Schema Specification Wright Draft 00](https://json-schema.org/), which technically it's not quite JSONSchema. Moreover, it explicitly says that it could be extended with spec extensions (see the bottom of [this section](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#schema-object)).

> but how is it possible to ignore a specific property name (Not rule)? It must work for all occurrences of the property.

The ignore file is created automatically and allow to ignore all current errors. Please take a look at [the docs](https://redocly.com/docs/cli/commands/lint#generate-ignore-file).

**Comment by goldingdamien** [comment]
"This object MAY be extended with [Specification Extensions](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#specification-extensions)." - Thanks. I'll recommend this if the other methods are too much trouble.

"The ignore file is created automatically and allow to ignore all current errors. " - Oh, interesting, I'll check out the docs.

Those 2 solutions, should be enough to fix the error.
Thank you for your time.
