### ISSUE TITLE
Run redocly command programmatically from node JS code

### ISSUE THREAD

**Issue by gituserjava** [Redocly/redocly-cli#1726]
How do I run below redocly command programmatically from Node JS program?

```
redocly build-docs games@v1
```

Please advise.

**Comment by tatomyr** [comment]
Hi @gituserjava, what's your use case?

**Comment by gituserjava** [comment]
@tatomyr ,

did you get a chance to look into this comment?

**Comment by tatomyr** [comment]
There's no exported interface for the `build-docs` command which you can use directly in your code. However, it should be possible to create a chain of commands to fetch the file, then store it somewhere on the filesystem, then run the `redocly build-docs <path-to-the-file>` (as a NodeJS child process), and then read the output from the stored file. Please let me know if that helps. 

Anyway, it's not a bug, so I'm closing the issue. Feel free to ping me if you need anything else.

**Comment by tatomyr** [comment]
@gituserjava you can try [execSync](https://nodejs.org/api/child_process.html#child_processexecsynccommand-options).
