### ISSUE TITLE
Incorrect docs regarding `build-docs` output having zero dependencies

### ISSUE THREAD

**Issue by Foxcapades** [Redocly/redocly-cli#1731]
**Describe the bug**

The Redocly CLI documentation at https://redocly.com/docs/redoc/deployment/cli explicitly states that the output of the `build-docs` process will be "a zero-dependency HTML file" however there does not appear to be an any documented method of producing an HTML output that is not dependent on an external instance of the redoc JS file.

**To Reproduce**

1. Given any valid api yaml input
2. Run the command `redocly build-docs {some-api-def}`
3. See html -> head -> script element in generated output for link to https://cdn.redoc.ly/redoc/v2.1.5/bundles/redoc.standalone.js

**Expected behavior**

Expected output to require zero dependencies, as per docs.

**Redocly Version(s)**

```json
    "@redocly/cli": "^1.25.0"
```

**`Node.js` Version(s)**

`Node.js v21.1.0`

**OS, environment**

Ubuntu 24.04.1 LTS

**Comment by lornajane** [comment]
Thanks @Foxcapades , the docs have outdated information there. I'll get them updated.
