### ISSUE TITLE
Fix broken links on push command page

### ISSUE THREAD

**Issue by HCloward** [Redocly/redocly-cli#1779]
**Describe the bug**

There are two broken links on the push command page including a link to Organization slug and one to Project slug.

**To Reproduce**

1. Go to https://redocly.com/docs/cli/commands/push
2. Click Organization slug or Project slug in the Command options table.
3. See a 404 page.

**Expected behavior**

We need to either delete the links and put the info direction in the table, or add back the content that was removed in the Realm docs.

This was noted in a [feedback report on the embedded docs project](https://app.cloud.redocly.com/org/redocly/project/embedded-docs/feedback/fb_01hnj28eqpfj0h73ctsgkvpy5w).

**Comment by lornajane** [comment]
I think this might have been a partial when it was still in the monorepo docs. But we should try to avoid partials and other markdoc tags for the open source project docs.
