### ISSUE TITLE
Does it support offline use

### ISSUE THREAD

**Issue by houxinlin** [Redocly/redocly-cli#1801]
Does it support offline use

The generated HTML includes the cdn ` redoc.standalone.js ` script, but my computer is offline and has no network, so I cannot use it. Can I support embedding script content into HTML instead of introducing external resources

**Comment by tatomyr** [comment]
Redocly CLI doesn't support that out of the box. If you're interested in offline usage, please check this issue: https://github.com/Redocly/redocly-cli/issues/1035.

**Comment by houxinlin** [comment]
My idea is to modify the source code by directly inserting the source code of 'redoc. standalone. js' into the<script>during generation, instead of using src.

If this is possible, where can I find uncompressed 'redoc. standalone. js'? Thank you

**Comment by tatomyr** [comment]
You can find the sources in the official repository: https://github.com/Redocly/redoc
