### ISSUE TITLE
Add validation rule for declaring form parameter and body in OAS 2.0

### ISSUE THREAD

**Issue by AntonKozachuk** [Redocly/redocly-cli#249]
**Is your feature request related to a problem? Please describe.**
Since form parameters are sent in the payload, they cannot be declared together with a body parameter for the same operation - according to the [OAS 2.0 docs](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameterObject). 

**Describe the solution you'd like**
Need to have a validation rule for this case. 

**Describe alternatives you've considered**
n/a

**Additional context**
None.

**Comment by lornajane** [comment]
Adding more core functionality for older spec versions isn't a priority. Users should use configurable rules or custom plugins for any additional features beyond the current feature set.
