### ISSUE TITLE
Add --config option to the join command

### ISSUE THREAD

**Issue by AntonKozachuk** [Redocly/redocly-cli#254]
**Is your feature request related to a problem? Please describe.**
Let's say I have 3 open API YAML files that belong to a single project. I need to combine all of them then I need to generate single HTML documentation for the entire project.

**Describe the solution you'd like**
Add --config option to the `join` command similar to the `bundle` command.
Under API definitions of the config file .redocly.yaml we can have the paths to each file that need to be joined. 

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by lornajane** [comment]
I think it makes sense to allow the user to specify a config file, but that the API names/files to join should still be supplied to the command. Joining everything in the config file is probably not what a user intended in most cases.

**Comment by tatomyr** [comment]
Has been implemented in scope of https://github.com/Redocly/redocly-cli/pull/1136.
