### ISSUE TITLE
Add an additional info to the 'openapi-cli push' error to have a more clear picture of what exactly is wrong

### ISSUE THREAD

**Issue by olgaStadnyk** [Redocly/redocly-cli#265]
**Describe the bug**
When user swap places of the file name and version data, the error below is shown.
And it hard to understand what exactly is wrong. Would be nice to insert the 'Wrong' value into the error
![image](https://user-images.githubusercontent.com/16819277/111146788-80f21400-8592-11eb-934b-58dd560cf176.png)

**To Reproduce**
![image](https://user-images.githubusercontent.com/16819277/111147249-ef36d680-8592-11eb-88ad-d29b203575b8.png)

**Expected behavior**
Destination argument value **openapi.yaml** is not valid, please use the right format: <@organization-id/api-name@api-version>

**Comment by lornajane** [comment]
I think this is covered by the updates to the `push` command made for the 1.0 release, so I'll close this but please let us know if this still seems to be a problem.
