### ISSUE TITLE
Option for join to not create x-tagGroups

### ISSUE THREAD

**Issue by steve-nay-sage** [Redocly/redocly-cli#359]
**Is your feature request related to a problem? Please describe.**
I was surprised to read this about the `openapi join` command:

>if any of the input files contains the tags object, the join command automatically creates the x-tagGroups object in the output file

and

>If any of the input files contains the x-tagGroups object, the content of this object is ignored by the join command, and not included in the output file.

Essentially, that means that I can't use x-tagGroups. If I put it in any of the input files, the join command is going to ignore it. What the join command creates automatically from my input files is essentially a duplicate of the tags list; every tag appears in the tags list, and every x-tagGroup contains only one tag. The only benefit is that join also brings in the info:description, but that's of questionable value if tags also have descriptions.

Join also puts any untagged operations as xyz_other in x-tagGroups, but that's of questionable value, too, and buggy. 

**Describe the solution you'd like**
I would like the `join` command to have an option flag to do this with x-tagGroups:

- Don't create it automatically in the output file
- If the first input file contains x-tagGroups, include it in the output file and ignore x-tagGroups from any of the other input files.
- If the first input file does not contain x-tagGroups but other files do, merge those together in the output file, the same way that tags are merged. 

This option would let me be in control of what's in x-tagGroups instead of the join command making that decision for me. I could fully define my x-tragGroups in the first input file, including descriptions and the list of tags in each group. I see this as very synonymous with how all of the `info` properties are read from the first input file and ignored in all other input files.

**Comment by adamaltman** [comment]
I like the idea. I wonder which of these should be the default behavior:

- Do nothing
- Create it automatically
- Use the first x-tagGroups
- Combine all x-tagGroups

**Comment by steve-nay-sage** [comment]
I don't know that you have to choose one from that list of four. I think you can get the first, third, and fourth bullets at the same time with this logic:
1. If the first file contains x-tagGroups, use that.
2. If the first file does not contain x-tagGroups but you find it in any other files, combine them.
3. If you don't find x-tagGroups in any files, do nothing. 

It's only that last one that's a question: if none of the files have x-tagGroups, should you do nothing or create it automatically? The information that I'd want to help decide that is, does an automatically created x-tagGroups really provide a valuable organization of the tags? Like I said in the original request, for my use case it was essentially a duplicate of the tags list, so didn't add much value. 

Another bit of logic that you might want to consider is what to do if the join finds any operations without tags. The current strategy tags them with _other so that they show up in a group, but how should that play with the above logic? I haven't worked through that one because I try to tag everything.

**Comment by steve-nay-sage** [comment]
@RomanHotsiy I'd like to vote for this issue to be given a higher priority because join currently always creates x-tagGroups (assuming the OpenAPI files contain tags) but they are just redundant of the existing tags; they add no value. Worse than that, they have to be removed because they look pretty bad in Redocly. (See my original description about why they are worthless.)
x-tagGroups is a nice feature, but the join command isn't applying it correctly.
