### ISSUE TITLE
Docs: unresolved issues that need clarification

### ISSUE THREAD

**Issue by bandantonio** [Redocly/redocly-cli#380]
This issue is a glossary of all the problems with the documentation that haven't been addressed yet:
* [x] - #350:
  * [x] - Which criteria are used for linting if this option is set to `true`? Does it use the lint settings from the config file? What if the option is set to `true` but there is no config file?
* [x] - #361:
  * [x] - Are there any restrictions related to ports; which ports are supported? Can users put just any number here?
* [x]  - #363:
  * [x] - `--run-id` Do you think it would be useful to investigate and mention a couple of use-cases or reasons why a user would want to do something like this?
* [x] - #360
  * [x] - How does this `--extends` option work - how to use it, what does the output look like when it's used? It should have its own section with an example, like the other options do.

### Post-review
* [x] - Inconsistent description of CLI commands [needs re-review after merging all the PRs]
  * [x] - Issue: The branchName seems to be removed from all the examples. It is a common use case.

### Bugs
* [x] - #370
* [x] - #371 
* [x] - #372

**Comment by adamaltman** [comment]
I read this with a Google search:

> Ports 0 through 1023 are defined as well-known ports. Registered ports are from 1024 to 49151. The remainder of the ports from 49152 to 65535 can be used dynamically by applications.

I think we can use any available well-known or registered ports.

**Comment by adamaltman** [comment]
>  - Which criteria are used for linting if this option is set to true? Does it use the lint settings from the config file? What if the option is set to true but there is no config file?

If it is true, then it uses the lint settings from the config file. If there are no lint settings it uses the default lint.

**Comment by bandantonio** [comment]
@adamaltman I will add information about `--lint` during the final review stage. I believe this affects both `bundle` and `lint` commands, as the latter can also be used without passing the config explicitly.
