### ISSUE TITLE
`join` command with `--prefix-components-with-info-prop` looses additional schemes in security requirement

### ISSUE THREAD

**Issue by simon-spinner** [Redocly/redocly-cli#401]
**Describe the bug**
A security requirement of an operation may specify multiple security schemes that all must be fulfilled. When using `join` with `--prefix-components-with-info-prop` only the first security scheme gets copied to the joined document

**To Reproduce**
1. Given no `.redocly.yaml` file
2. And this OpenAPI file(s)
openapi1.yaml:
```
openapi: 3.0.2
info:
  title: Spec1
  version: 1.0.0
servers:
  - url: 'https://localhost:8080/api'
paths:
  /example:
    get:
      responses:
        '200':
          description: OK
      security:
        - scheme1: []
          scheme2: []      
components:
  securitySchemes:
    scheme1:
      type: http
      scheme: basic
    scheme2:
      type: http
      scheme: basic
```
openapi2.yaml:
```
openapi: 3.0.2
info:
  title: Spec2
  version: 1.0.0
servers:
  - url: 'https://localhost:8080/api'
paths: {}
```

3. Run this command with these arguments... `openapi join --prefix-components-with-info-prop title openapi1.yaml openapi2.yaml`
4. See the resulting joined spec:

```
openapi: 3.0.2
info:
  title: Spec1
  version: 1.0.0
servers:
  - url: 'https://localhost:8080/api'
paths:
  /example:
    get:
      responses:
        '200':
          description: OK
      security:
        - Spec1_scheme1: []
      tags:
        - openapi1_other
tags:
  - name: openapi1_other
    x-displayName: other
x-tagGroups:
  - name: openapi1
    tags:
      - openapi1_other
components:
  securitySchemes:
    Spec1_scheme1:
      type: http
      scheme: basic
    Spec1_scheme2:
      type: http
      scheme: basic

```

**Expected behavior**
The operation `get /example` should have 2 security schemes: `Spec1_scheme1` and `Spec1_scheme2`. But it only contains `Spec1_scheme1`.

**`openapi-cli` Version(s)**
1.0.0-beta.54

**`Node.js` Version(s)**
v16.8.0

**Comment by tatomyr** [comment]
Hi @simon-spinner! 
We've just released v1.9.1 with the fix. Could you check if it works for you?
