### ISSUE TITLE
`preview-docs` hot reload not working

### ISSUE THREAD

**Issue by adamaltman** [Redocly/redocly-cli#424]
**Describe the bug**

Hot reload is not working for `preview-docs`.

**To Reproduce**
1. Given any `.redocly.yaml` file
2. And any OpenAPI file(s)
3. Run this command with these arguments... `openapi preview-docs`
4. Open browser
5. Make change and save file
6. See browser doesn't reload (this is the error)

**Expected behavior**

**Logs**

Created a bundle for openapi/auth-service.yaml successfully
GET /: 25.841ms
GET /simplewebsocket.min.js: 2.664ms
GET /hot.js: 0.524ms
GET /openapi.json: 2.461ms
GET /favicon.png: 1.826ms
GET /copper_logo_gradient.png: 0.926ms
watch changed /Users/adam/.redacted.md

Bundling...

Created a bundle for openapi/auth-service.yaml successfully
```

**`openapi-cli` Version(s)**

1.0.0-beta.65

**`Node.js` Version(s)**
What version of `node.js` are you using?

- v16.1.0
- Also tried 14 LTS.

**Comment by slavikbez** [comment]
@adamaltman I wasn't able to reproduce this problem. The page reloads when I make changes in the definition file.

https://user-images.githubusercontent.com/9461457/139729968-4f1ffde5-228d-49f2-9e8c-727f6108ac57.mov

**Comment by adamaltman** [comment]
@slavikbez this repo: https://github.com/Rebilly/api-definitions and I'm previewing with the premium reference docs (requires you to login first).

**Comment by slavikbez** [comment]
Located the problem: https://github.com/Redocly/openapi-cli/blob/master/packages/cli/src/commands/preview-docs/preview-server/preview-server.ts#L108

**NOTE** this problem exists only with `pagination` set to `item` or `section`

**Comment by adamaltman** [comment]
I have had the problem without pagination though too. I'm happy to check again after your fix.
