### ISSUE TITLE
`bundle` command squash referenced markdown file to one string

### ISSUE THREAD

**Issue by Boiarshinov** [Redocly/redocly-cli#481]
**Describe the bug**

`bundle` command squash referenced markdown file to one string.
I'm not sure is that a bug or a feature absence 😅 

**To Reproduce**
Given this OpenAPI file:
```yaml
openapi: 3.0.1
info:
  title: Demo API
  version: '1.0'
  description:
    $ref: './description.md'
paths: {}
```

Which has reference to this markdown description:
```markdown
# Heading
List:
- first item
- second item

Line.
Same Line
```

Run this command
```sh
openapi bundle openapi.yaml --output bundled.yaml
```

And look at the squashed description in the bundled file:
```yaml
openapi: 3.0.1
info:
  title: Demo API
  version: '1.0'
  description: "# Heading\r\nList:\r\n- first item\r\n- second item\r\n\r\nLine.\r\nSame Line"
paths: {}
components: {}
```

FYI: swagger-cli have the same behavior

**Expected behavior**
In my opinion it's better not to squash markdown file to single line but to use multiline strings in [literal mode](https://oai.github.io/Documentation/specification-docs.html#providing-long-descriptions-in-yaml).
So the expected bundled file should be:
```yaml
openapi: 3.0.1
info:
  title: Demo API
  version: '1.0'
  description: |
    # Heading
    List:
    - first item
    - second item

    Line.
    Same Line
paths: {}
components: {}
```

**`openapi-cli` Version(s)**
1.0.0-beta.74

**`Node.js` Version(s)**
v16.13.0

**Comment by iosypov** [comment]
I can not reproduce this. 

I tried file:
```yaml
openapi: 3.0.1
info:
  title: Demo API
  version: '1.0'
  description: "# Heading\r\nList:\r\n- first item\r\n- second item\r\n\r\nLine.\r\nSame Line"
paths: {}
components: {}
```

And get result:
```yaml
openapi: 3.0.1
info:
  title: Demo API
  version: '1.0'
  description: |
    # Heading

    List:

    - first item
    - second item

    Line.
    Same Line
paths: {}
components: {}
```

**Comment by Boiarshinov** [comment]
I've opened a PR with instructions how to reproduce an issue
https://github.com/Redocly/redocly-cli/pull/823
