### ISSUE TITLE
Environment variable support

### ISSUE THREAD

**Issue by adamaltman** [Redocly/redocly-cli#494]
**Is your feature request related to a problem? Please describe.**

The lint and bundle command behavior can be influenced in workflows by the environment variables `OPENAPI_CLI_BUNDLE_ARGS` and `OPENAPI_CLI_LINT_ARGS`. This behavior isn't reproduced by the CLI itself.

**Describe the solution you'd like**

- rename the environment variables to `REDOCLY_CLI_BUNDLE_ARGS` and `REDOCLY_CLI_LINT_ARGS`.
- document these environment variables within those commands
- define precedence (or behavior) of environment variables or given args.

This way the behavior becomes the responsibility of the CLI... and setting the values is the only responsibility of workflows (or however people are using the CLI). This will make it easier for people to test the CLI and easier to document the behaviors.

**Describe alternatives you've considered**

Doing nothing.

**Additional context**

Some [internal context](https://github.com/Redocly/marketing-site-portal/pull/682)

**Comment by lornajane** [comment]
The login command also works with environment variables, let's include these (and anything else related) in the documentation updates.

**Comment by tatomyr** [comment]
@adamaltman I'm just wondering if this is still valid

**Comment by RomanHotsiy** [comment]
@tatomyr yes.
