### ISSUE TITLE
preview-docs reload is not working anymore 

### ISSUE THREAD

**Issue by nbourguig** [Redocly/redocly-cli#538]
**Describe the bug**
Reloading browser is not working when openapi-cli is installed globally.

**To Reproduce**
1. Install openapi-cli globally 
2. Open any specs files using preview-docs command `openapi preview-docs openapi.yaml` 
3. Open the browser
4. Change anything in the spec file
5. Browser does not reload 

**Expected behavior**
The browser should reload content when the file is edited.

**Logs**
Browser cannot load `simplewebsocket.min.js` and `hot.js`
![image](https://user-images.githubusercontent.com/276832/151593879-64071d14-a4e3-465c-870f-bffab0966050.png)

**`openapi-cli` Version(s)**
1.0.0-beta.80

**`Node.js` Version(s)**
16.13.2

**Additional context**
After checking out, it seems that this recently[ introduced change](https://github.com/Redocly/openapi-cli/pull/347) is preventing the loading of the `hot.js` and `simplewebsocket.min.js` 

Commenting out [this specific code](https://github.com/Redocly/openapi-cli/blob/master/packages/cli/src/commands/preview-docs/preview-server/preview-server.ts#L110-L114) in the /lib folder resolves the issue.

**Comment by CarltonHowell** [comment]
I'm seeing the same issue
<img width="629" alt="Screen Shot 2022-03-17 at 1 44 12 PM" src="https://user-images.githubusercontent.com/54380672/158732743-9ecfe05e-467d-4a1b-a62a-17dce7e5809e.png">

**Comment by seamons** [comment]
I'm seeing the same issue as well.

**Comment by tatomyr** [comment]
Could only reproduce this with a published version of `openapi-cli` and not in local development environment.

**Comment by adamaltman** [comment]
I have the same issue.
