### ISSUE TITLE
Core package should not depend on colorette

### ISSUE THREAD

**Issue by akx** [Redocly/redocly-cli#539]
**Describe the bug**

The core package depends on `colorette` to be able to color error messages using ANSI codes.

That package attempts to read `process.env` during import time, which isn't a thing in browsers (unless transpiled), causing trouble trying to use `@redocly/openapi-core` with e.g. https://vitejs.dev/.

(Another related issue is `node-fetch`, which doesn't work OOTB in a Vite environment either.)

**To Reproduce**
1. Try to import `@redocly/openapi-core` 1.0.0-beta.80 in a non-bundling browser environment.

**Expected behavior**

The library should not depend on a console coloring library.

**Comment by AlexVarchuk** [comment]
It also relates to https://github.com/Redocly/redoc/issues/1820.

**Comment by roman-sainchuk** [comment]
Hello @akx
In `1.0.0-beta.108` was added browser support. We're still depending on `colorette` but it is not used in browser env.
Please let us know if you still have issues with it

**Comment by lornajane** [comment]
I think this has been fixed, so I'll close the issue but please let us know if this still causes a problem.
