### ISSUE TITLE
`operation-4xx-response` rule evaluates webhooks

### ISSUE THREAD

**Issue by adamaltman** [Redocly/redocly-cli#546]
**Describe the bug**

The `operation-4xx-response` rule evaluates webhooks (and x-webhooks), and that doesn't make sense because of the nature of webhooks (asking clients to implement an API to receive notifications is a big enough ask, let alone to ask them to implement error handling and some error response codes and schemas). Those should be skipped.

**To Reproduce**

Pull rebilly/api-definitions. Run openapi lint.

**Expected behavior**

Don't evaluate webhooks (or x-webhooks).

**Logs**
n/a

**OpenAPI definition**
3.0

**`openapi-cli` Version(s)**

1.0.0-beta.80

**`Node.js` Version(s)**

16.10

**Additional context**

Trying to make the rules make the most sense out of the box.

**Comment by IgorKarpiuk** [comment]
@adamaltman we have [option](https://redocly.com/docs/cli/rules/operation-4xx-response/#configuration) `validateWebhooks` with which we can disable the evaluation of webhooks

**Comment by lornajane** [comment]
Thanks @IgorKarpiuk! Your comment prompted me to take a look at this and I think what we have makes sense. The default value for `validateWebhooks` is `false`, so we normally don't run this rule on those endpoints, but it does correctly check them if I set it to true. I don't think there's more to do on this so I'll close the issue.
