### ISSUE TITLE
[Docs] Inconsistent tables in OpenAPI CLI command docs

### ISSUE THREAD

**Issue by ivana-isadora** [Redocly/redocly-cli#548]
**Is your feature request related to a problem? Please describe.**

We've recently simplified the **Options** table for [the bundle command](https://redoc.ly/docs/cli/commands/bundle/) by reducing the amount of columns and moving the relevant information from deleted columns into the **Description** column.

To make our documentation consistent, we need to do this for all the other OpenAPI CLI commands; namely:

- [join](https://redoc.ly/docs/cli/commands/join/)
- [lint](https://redoc.ly/docs/cli/commands/lint/)
- [login](https://redoc.ly/docs/cli/commands/login/)
- [logout](https://redoc.ly/docs/cli/commands/logout/)
- [preview-docs](https://redoc.ly/docs/cli/commands/preview-docs/)
- [push](https://redoc.ly/docs/cli/commands/push/)
- [split](https://redoc.ly/docs/cli/commands/split/)
- [stats](https://redoc.ly/docs/cli/commands/stats/)

**Describe the solution you'd like**

Every command page should have the **Options** table formatted the same way as the `bundle` page currently has.

**Additional context**

**This task is reserved for our OSS tech writer.** Please do not (re)assign it to anyone else.

**Comment by Preshh0** [comment]
Hi @lornajane, are you still working on this?

**Comment by lornajane** [comment]
It's assigned to me because I think this has been done but I need to check before closing.

**Comment by Preshh0** [comment]
Okay. I'm sorry I skipped that part.

**Comment by lornajane** [comment]
Pages have been updated
