### ISSUE TITLE
Replace minimatch with zero-dep picomatch

### ISSUE THREAD

**Issue by RomanHotsiy** [Redocly/redocly-cli#635]
**Describe the solution you'd like**
Replace minimatch module with zero-dep picomatch: https://www.npmjs.com/package/picomatch

**Additional context**
Less dependencies is always good.

**Comment by lornajane** [comment]
Does this still seem relevant @RomanHotsiy ? I realise this one has been open a while

**Comment by RomanHotsiy** [comment]
I remember someone tried it but for some reason it didn't work out. @tatomyr do you remember it maybe? Or am I confusing something?

**Comment by RomanHotsiy** [comment]
But I just checked it more. I think we should stick with minimatch.
The bundle size is same, picomatch is 2x faster though, but we're not using it on hot path.

I'm closing it.
