### ISSUE TITLE
`ref` assertions

### ISSUE THREAD

**Issue by adamaltman** [Redocly/redocly-cli#648]
**Is your feature request related to a problem? Please describe.**

I want to be able to detect if a particular type of thing is defined using a `$ref`, and in particular a `$ref` to a separate file or url.

**Describe the solution you'd like**

Option A is flatter and has two data types (which is a bit unorthodox).

Option B requires a nested object, which is a different type of complexity.

Which is the less of the two evils?

## Option A

Add to the `Assertion Object`:
| Property | Type | Description |
|---|---|---|
|`ref`| string \| boolean | Evaluates the subject's property. A boolean value of `true` means the property has a `$ref` defined. A boolean value of `false` means the property has not defined a `$ref` (it has an in-place value). A string value means that the `$ref` is defined and the unresolved value must match the pattern (for example, `'/paths\/.*\.yaml$/'`).    | 

Example with pattern

```yaml
subject: PathItem
ref:  '/paths\/.*\.yaml$/'
```
Example with defined
```yaml
subject: PathItem
ref: true
```

## Option B

Add to the `Assertion Object`:
| Property | Type | Description |
|---|---|---|
|`ref`|Ref assertion object|Asserts that the subject property meets the corresponding ref assertion.| 

### Ref assertion object

| Property | Type | Description |
|---|---|---|
|undefined|boolean|Set to true means there is not a `$ref` defined for the subject property.|
|pattern|string|Pattern checked against the unresolved `$ref` value. For example, `'/paths\/.*\.yaml$/'`.|

Example with pattern

```yaml
subject: PathItem
ref:
  pattern: '/paths\/.*\.yaml$/'
```
Example with defined
```yaml
subject: PathItem
ref:
  undefined: false
```

**Describe alternatives you've considered**

Multiple boolean properties like `isRef`, `isFileRef`, `isUrlRef`.

**Additional context**

To enforce that PathItems are made using `$ref` to a separate file. To enforce that request and response schemas are made using a `$ref` to a separate "any" `$ref` schema.

**Comment by RomanHotsiy** [comment]
I like A) more in terms of UX. The B) is more flexible though if we decide to add other asserts to the ref string.
But I lean towards A) though.
