### ISSUE TITLE
Callbacks typing seems wrong

### ISSUE THREAD

**Issue by adamaltman** [Redocly/redocly-cli#664]
**Describe the bug**

The NamedCallbacks and Callback types seem wrong.

```js
  NamedCallbacks: mapOf('PathItem'),
``` 
Note: Seems like it should be a `mapOf('Callback')`.

And

```js
const Callback = {
  properties: {},
  additionalProperties: 'PathItem',
};
```

This seems incorrect. The callback is a map of expression to `PathItem`. It seems it should be more similar to:

```js
  Callback: mapOf('PathItem'),
```

**To Reproduce**
Steps to reproduce the behavior (minimal definition):

```yaml
openapi: 3.1.0
info:
  title: Callback test
  version: 'alpha'
components:
  callbacks:
    resultCallback:
      '{$url}':
        post:
          requestBody:
            description: Callback payload
            content:
              'application/json':
                schema:
                  type: object
                  properties:
                    test:
                      type: string
          responses:
            '200':
              description: callback successfully processed

```

Run `openapi lint`.

```
Property `{$url}` is not expected here.

 6 | callbacks:
 7 |   resultCallback:
 8 |     '{$url}':
 9 |       post:
10 |         requestBody:

Error was generated by the spec rule.
```

**Expected behavior**
I expected that the callback is correct. If not, what is wrong?

**Logs**

```
Property `{$url}` is not expected here.

 6 | callbacks:
 7 |   resultCallback:
 8 |     '{$url}':
 9 |       post:
10 |         requestBody:

Error was generated by the spec rule.
```

**`openapi-cli` Version(s)**

1.0.0-beta.94

**`Node.js` Version(s)**

16

**Additional context**

None

**Comment by RomanHotsiy** [comment]
Raising the priority as the fix is suggested in the issue itself and should take under 1 hour (with tests) to implement.
