### ISSUE TITLE
For join, the same tag in multiple input files should not be seen as a conflict

### ISSUE THREAD

**Issue by steve-nay-sage** [Redocly/redocly-cli#668]
**Problem**
I have two (or more) OAS files that use the same tag to tag some operations. Running `openapi join` results in an error about "Conflict on tags."

**Improved Solution**
I don't see why it would be considered a conflict if multiple schemas that you're trying to join together use the same tag names. Maybe display a warning, but it's not an irreconcilable crisis that should prevent the join from succeeding. Use the first (or the last) description of the tag--authors can figure that out. 

This is what is already done with components that are defined in multiple input files but are identical. It's not considered an error.

Perhaps have a command line option to let the user choose what to do if the same tag name is used in multiple files:
1. Allow it.
2. Error out.
3. Prefix with info property
4. Prefix with filename

**Describe alternatives you've considered**
I tried using prefix-tags-with-info-prop but that gave me different tags with goofy names, which was not at all useful.

**Comment by SmoliyY** [comment]
Currently, we have a few options to resolve this case:

- Allow duplication of `tags` in `x-tagGroups` (this will need improvements of navigation in ReferenceDocs)
- Skip population and creation of `x-tagGroups` at all

What do you think? @adamaltman @RomanHotsiy

**Comment by RomanHotsiy** [comment]
Let's discuss it on a call. I don't remember how join works already. Need to refresh my memory 😄

**Comment by SmoliyY** [comment]
After discussion with @RomanHotsiy we agreed to go with second option by specifying `option` that will allow skip population of `x-tagGroups`.

**Comment by SmoliyY** [comment]
Hi, @steve-nay-sage in `redocly/cli` release `1.0.0-beta.102` you may now use `--without-x-tag-groups` option for `join` command;

If you have the same tags in multiple definitions you can allow duplication by using the `without-x-tag-groups` option. In this case, the `x-tagGroups` property wouldn't be created. 

```bash Command
redocly join first-api.yaml second-api.json --without-x-tag-groups
```

The tag description is taken from first match.

Note: options `without-x-tag-groups`, `prefix-tags-with-filename`, and `prefix-tags-with-info-prop` are mutually exclusive.

More docs will be soon.
