### ISSUE TITLE
Suggestion to improve the readme description

### ISSUE THREAD

**Issue by StephenNay** [Redocly/redocly-cli#67]
The description of openapi-cli talks about "bundling" and that the "startingPoint" is the "root document," but it doesn't say anywhere how the multiple files are at all related. I assume that the root file is supposed to have $ref references to other files, but the readme doesn't say that and there is no example shown. An example and just a little more explanation would go a long way on this.

**Comment by knidarkness** [comment]
Hello, @StephenNay. Thank you for your attention and involvement. We will definitely update the README. It was not finalized yet, as before the v1 release the API can change quite substantially. However, now that should not be a case anymore, so it's the right time to get better docs.

**Comment by adamaltman** [comment]
I think we'll add these examples primarily by linking to the generator repo (once we release it with the new format).
