### ISSUE TITLE
Not correct validation $ref in properties

### ISSUE THREAD

**Issue by AlexVarchuk** [Redocly/redocly-cli#682]
**Describe the bug**
The lint command should mark this schema as invalid.

**To Reproduce**
1. run the lint command with the example of the definition

**Expected behavior**
Should report a problem with $ref. $ref cannot use in `properties` like in the example

**OpenAPI definition**
_openapi.yaml_
```
paths:
  /pet:
    get:
      operationId: example
      summary: summary example
      responses:
        '200':
          description: example description
          content:
            application/json:
              schema:
                type: object
                properties:
                  $ref: './nestedRef.yaml'
                  name:
                    type: string

```
_nestedRef.yaml_
```
total:
  description: Total data number
  type: number
  example: 1000
pages:
  description: Total pages
  type: number
  example: 5
```

**Redocly Version(s)**
1.0.0-beta.97

**Node.js Version(s)**
15

**Comment by lornajane** [comment]
We should change this behaviour with our upcoming major release.
