### ISSUE TITLE
# symbol is not properly encoded while forming the $ref path

### ISSUE THREAD

**Issue by nalesnichok** [Redocly/redocly-cli#685]
***Describe the issue**

 The # symbol in C# code samples is not encoded properly if we run `openapi bundle` command.

**To Reproduce**

1. Add C# `x-codeSamples` to your definition file - `- lang: C#`
2. Run `openapi split` command on your definition
3. Run `openapi bundle` command after that
4. Notice the error messages:
<img width="933" alt="Screenshot 2022-05-13 at 18 17 35" src="https://user-images.githubusercontent.com/59624019/168314701-0a558234-c887-49f3-8a27-2eaa41767d97.png">

**Expected behavior**
(#) symbol should be properly encoded while forming the $ref path. As a workaround, we can replace `-lang: C#` to `-lang: C-sharp` for example, and it will solve the problem

**OpenAPI definition**

openapi: 3.0.0

What version of Redocly CLI are you using?

1.0.0-beta.94

**`Node.js` Version(s)**

v16.13.1

**Comment by adamaltman** [comment]
I don't think this is a bug. Use `-lang: 'C#'`.
https://intranet.redoc.ly/skills/yaml/documents-comments/#comments

**Comment by nalesnichok** [comment]
@adamaltman  the above didn't help. I'm still getting the same error message:

<img width="923" alt="Screenshot 2022-05-15 at 22 22 49" src="https://user-images.githubusercontent.com/59624019/168490301-39b49aef-b939-419f-b73e-2b246ea08b7f.png">

The octothorpe is ignored when the $ref path is forming

**Comment by adamaltman** [comment]
You have the same issue in the line below.  The $ref should be `$ref: '...' because the value has the octothorpe. This is YAML.

**Comment by tatomyr** [comment]
@adamaltman, I believe there's still an issue with the `split` command that produces the wrong ref. 
I'm reopening and assigning this to @AntonKozachuk to investigate further.
