### ISSUE TITLE
`push` command: ability to upload other files 

### ISSUE THREAD

**Issue by RomanHotsiy** [Redocly/redocly-cli#699]
**Is your feature request related to a problem? Please describe.**
Our workflows app allows users to upload other files next to the openapi definition.

![image](https://user-images.githubusercontent.com/3975738/169823078-53c0c3d5-98c5-4447-bb9e-1bc0c6a7c73c.png)

Our `push` command doesn't have the same capabilities.

**Describe the solution you'd like**

Add a new argument to the `push` command: `--files`.

```sh
redocly push openapi/petstore.yaml @openapi-org/petstore-api@v1 --files ./files
```

Also, we may need to add `files` config to the redocly.yaml.

**Describe alternatives you've considered**
None.

**Additional context**
Should work similar to manual files upload.

**Comment by adamaltman** [comment]
> Also, we may need to add `files` config to the `redocly.yaml`.

What possible configurations are there? Defining a list of files so that the argument can be avoided?

**Comment by adamaltman** [comment]
I opened a can of worms. 🪱 🪱 

It could also be a list of folders.

```yaml
files:
  - ./xray
  - ./zebra
```

Also, are they with or without trailing slashes?

**Comment by RomanHotsiy** [comment]
> It could also be a list of folders.

It's a little confusing why it's called `files` then. Or I overcomplicate?

> Also, are they with or without trailing slashes?

Doesn't matter.
