### ISSUE TITLE
discriminator example validation error with `anyOf`

### ISSUE THREAD

**Issue by adamaltman** [Redocly/redocly-cli#700]
**Describe the bug**

The discriminator is valid with `anyOf` but get this message:

> Example validation errored: discriminator: requires oneOf keyword.

**To Reproduce**
1. I have a private repo I can share with you...
2. See error

**Expected behavior**

It should work with `anyOf` too.

**Logs**

> Example validation errored: discriminator: requires oneOf keyword.

**OpenAPI definition**
3.0.0

**Redocly Version(s)**
redocly --version
1.0.0-beta.98

**`Node.js` Version(s)**
16

**Additional context**
none

**Comment by RomanHotsiy** [comment]
Looks like it's coming from AJV: https://github.com/ajv-validator/ajv/blob/95b15b683dfb60f63c5129b0426629b968d53af8/lib/vocabularies/discriminator/index.ts#L33

**Comment by adamaltman** [comment]
Can we propose a fix or fork it?

**Comment by AntonKozachuk** [comment]
@adamaltman we already have a fork - https://github.com/Redocly/ajv
I believe we can fix it there.

**Comment by adamaltman** [comment]
Thanks @AntonKozachuk ! I left a few comments on the messages in that PR.

**Comment by AntonKozachuk** [comment]
This issue is partially reliant on this one - https://github.com/orgs/Redocly/projects/9/views/3
