### ISSUE TITLE
Add a flag/command allowing to delete a branch

### ISSUE THREAD

**Issue by romanpryshliak** [Redocly/redocly-cli#726]
**Is your feature request related to a problem? Please describe.**

Add a flag/command to delete a published branch for an API definition via the CLI command.

Currently, the only way to delete a published branch is via the Workflows.

![image](https://user-images.githubusercontent.com/92374352/172619798-db1989a6-a203-4303-bcd3-2c61d9bec3e2.png)

**Describe the solution you'd like:**

Something like:

`openapi push api-definition @orgId/api-definition@version -D --branch branch-name`

or 

`openapi delete api-definition @orgId/api-definition@version --branch branch-name`

**Additional context:**

https://app.frontapp.com/open/cnv_lt2lf2k

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_481qk)

**Comment by lornajane** [comment]
We're unlikely to make changes for the workflows version of the push command at this stage, so I'm closing.
