### ISSUE TITLE
Use join command to unify all references

### ISSUE THREAD

**Issue by roukmoute** [Redocly/redocly-cli#752]
**Is your feature request related to a problem? Please describe.**

A possibility to unify via `join` command (or another) all references in one file.
Currently it does not understand the [yaml file that does not have certains key](https://github.com/Redocly/redocly-cli/blob/195fa94187f4dbed5cd04a7bd5c25c5cfc20fbb0/packages/core/src/oas-types.ts#L33-L35).

**Describe the solution you'd like**

```sh
➤ openapi-cli join openapi.yaml paths/*.yaml
Yeah!
```

**Additional context**

If I take [openapi-stater repository](https://github.com/Redocly/openapi-starter) like example I've got this:

```sh
➤ git clone git@github.com:Redocly/openapi-starter.git
➤  cd openapi-starter/openapi
➤ docker run --rm -v $PWD:/spec redocly/openapi-cli --version
1.0.0-beta.103
➤ docker run --rm -v $PWD:/spec redocly/openapi-cli join openapi.yaml paths/*.yaml
This doesn’t look like an OpenAPI document.
: /spec/paths/echo.yaml
```

**Comment by tatomyr** [comment]
As per [documentation](https://redocly.com/docs/cli/commands/join/#introduction) `join` isn't intended for joining a random json-schemas but rather for whole definitions. 
A'm not entirely sure, but it seems that you're probably looking for [`bundle`](https://redocly.com/docs/cli/commands/bundle/#bundle) command: `redocly bundle openapi.yaml [--dereferenced]`.

**Comment by roukmoute** [comment]
Perfect, I haven't seen `bundle` command.

**Comment by miestasmia** [comment]
@roukmoute Did you get it to work with `bundle`? I get the same error as with `join`. Is there really no way to reference paths like in [swagger-repo](https://github.com/Redocly/swagger-repo)?

**Comment by tatomyr** [comment]
@miestasmia could you elaborate what you're trying to achieve and what error you're getting?
