### ISSUE TITLE
Add the possibility to skip assertions

### ISSUE THREAD

**Issue by tatomyr** [Redocly/redocly-cli#765]
**Is your feature request related to a problem? Please describe.**

It is not possible to skip an assertion, since `--skip-rule` option doesn't work for assertions. 

**Describe the solution you'd like**

Either `--skip-rule` option should accept assertions as rules or we have to implement an option like `--skip-assertion`.

**Describe alternatives you've considered**
As a workaround we can "skip" an assertion by having two different `apis` lint configurations.

**Comment by lornajane** [comment]
I'm leaning towards the alternative solution here: have people configure different profiles rather than skipping at run time.

**Comment by tatomyr** [comment]
We haven't received any complains on that matter as far as I'm aware, and there's a way to do that via config, so I'm closing this.
