### ISSUE TITLE
Add additional options to push command

### ISSUE THREAD

**Issue by Orest-Yastremskyy** [Redocly/redocly-cli#768]
We would like to have an option to disable API docs builds for initial builds using push command.

Thus to add something like --skip-initial-build or skip-preview-branch-build to disable builds starting from the initial push.

This should work similar to the option we have in our UI:

![image](https://user-images.githubusercontent.com/96121440/179228077-41f37a55-a1f3-441a-8a87-5bb476a5894c.png)

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_4e7rg)

**Comment by Marshevskyy** [comment]
we already implemented similar functionality https://github.com/Redocly/workflows/issues/1958
can be useful for this issue

**Comment by lornajane** [comment]
Closing as I don't think we need this any more.
