### ISSUE TITLE
Mismatch between rules ids in docs and in-code

### ISSUE THREAD

**Issue by rvelaVenafi** [Redocly/redocly-cli#812]
**Describe the bug**

https://redocly.com/docs/cli/rules/no-server-example-com/
https://redocly.com/docs/cli/rules/no-empty-enum-servers/

In these two doc pages the rule id documented is different to what is actually used in code. 
When using  `no-server-example-com`, in-code the id is `no-server-example.com`
When using `no-empty-enum-servers` in-code the id is `no-servers-empty-enum`

Because of this, when using the documented rule ids, and running `redocly lint`, the output will throw the `<Property> not expected here` warning.
Also, these rules are not validated given that the rule id was not found.

**To Reproduce**
1. Given this `redocly.yaml` file:
```---
styleguide:
  extends:
    - recommended
  rules:
    no-empty-enum-servers: error
    no-server-example-com: error
```
3. And any OpenAPI file
4. Run this command with these arguments... `redocly lint`
5. See error

**Expected behavior**
Either documentation gets updated to use the correct in-code rule ids, or in-code rule ids get updated to match documentation

**Logs**
```
[1] redocly.yaml:8:5 at #/styleguide/rules/no-empty-enum-servers

Property `no-empty-enum-servers` is not expected here.

 6 |   - recommended
 7 | rules:
 8 |   no-empty-enum-servers: error
 9 |   no-server-example-com: error
10 |

Warning was generated by the configuration spec rule.


[2] redocly.yaml:9:5 at #/styleguide/rules/no-server-example-com

Property `no-server-example-com` is not expected here.

 7 | rules:
 8 |   no-empty-enum-servers: error
 9 |   no-server-example-com: error
10 |

Warning was generated by the configuration spec rule.


You have 2 warnings.
validating /test.json...
/test.json: validated in 19ms

Woohoo! Your OpenAPI definition is valid. 🎉
```

**OpenAPI definition**

OpenAPI definition: any
redocly.yaml file:
```
---
apis:
  test:
    root: ./test.json
styleguide:
  extends:
    - recommended
  rules:
    no-empty-enum-servers: error
    no-server-example-com: error
```

**Redocly Version(s)**
1.0.0-beta.106

**`Node.js` Version(s)**
v18.2.0

**Additional context**
N/A

**Comment by adamaltman** [comment]
I think we should fix the docs in both of these cases.

**Comment by adamaltman** [comment]
On second thought, I think we should fix https://github.com/Redocly/redocly-cli/blob/master/packages/core/src/rules/oas3/no-servers-empty-enum.ts to be `no-server-variables-empty-enum` because that is a more accurate summary.

**Comment by adamaltman** [comment]
@rvelaVenafi :

I should have noted this needs to await a release for you to be able to use the new rule name:

https://redocly.com/docs/cli/changelog/

(It should happen on Tuesday or Wednesday of next week.)
