### ISSUE TITLE
Provide node bindings/exports

### ISSUE THREAD

**Issue by fgblomqvist** [Redocly/redocly-cli#832]
**Is your feature request related to a problem? Please describe.**
It's not ideal to run the binary of this from within a node project, since it makes input/output as well as path resolving more complex than it should be.

**Describe the solution you'd like**
Be able to import the `@redocly/cli` package and run it from within node.

**Describe alternatives you've consideree**
Running it like a usual binary, or re-implementing the features we need from it ourselves.

**Comment by tatomyr** [comment]
Hi @fgblomqvist,

Which features exactly do you need from Redocly CLI?

**Comment by tatomyr** [comment]
Maybe if you explain what you're trying to achieve, I can suggest you a better solution?

**Comment by craftWolf** [comment]
Our goal is to create an CLI tool, for internal use, that would use certain functionality, implemented by the `redocly-cli` such as `bundle` or `lint`, as subcomands. To integrate `redocly-cli` in our tool we have 2 options:
* use `child_process.spawn("npx redocly-cli [command]")` which is not ideal,
* use `openapi-core` which does lacks docs explaining the config options, is missing quality of live improvements such as prettifying the output, `yaml<->json` schema conversion, linting/bundle defaults.

Note: correct me if I am wrong but the `redocly-cli` also has some logic regarding the configs, and remaps/transforms them before passing them to `openapi-core`.
Note: maybe there is a 3rd option to integrate `redocly-cli` functionality into our node based CLI, we would love to hear it from you.

**Comment by RomanHotsiy** [comment]
@craftWolf I see your point. I'm sorry but we would try to avoid exposing any public API from the CLI package (unless we see more demand for it, right now it's only you).

A few reasons:
- we have to maintain this newly added code
- we can't break it if we need it for some reason
- usage as a lib may will uncover some edge cases that we'll need to fix and maintain
- it needs some refactoring of CLI package

I have a few potential workarounds for you:

- сontinue using binary, I would not say it adds way too much overhead, especially if you use `--format json`.
- fork and maintain your own fork with the changes you need
- use openapi-core but copy the required code from the cli

Thank you for your understanding!
