### ISSUE TITLE
Flatten configuration file by removing styleguide object

### ISSUE THREAD

**Issue by adamaltman** [Redocly/redocly-cli#833]
**Is your feature request related to a problem? Please describe.**

The configuration file has one extra level of nesting which isn't required.
This makes docs and copy/paste more difficult than it needs to be.

**Describe the solution you'd like**

- Move `doNotResolveExamples` to the `resolve` object.
- Move `extends`, `plugins`, `rules`, `decorators`, `preprocessors` to the root.
- Support `rules`, `decorators`, and `preprocessors` in the `apis` object too.

- I adjusted all the documentation here: https://github.com/Redocly/marketing-site-portal/pull/986

**Describe alternatives you've considered**

Do nothing. But the time to do it is now, before we have a general release.

**Additional context**

- Notice the number of lines we can remove from the docs. 
- This makes copy/paste of configs easier too.

**Comment by tatomyr** [comment]
@adamaltman do we want to continue support `extends` and `doNotResolveExamples` in `apis` also (I see you haven't mentioned it in the changes)?
Please note that if we do want this for `doNotResolveExamples`, we would have to support the `resolve` object in `apis` as well.

**Comment by adamaltman** [comment]
Let's support the `extends` in `apis` too. Let's not support the `doNotResolveExamples` in `apis`.
