### ISSUE TITLE
A schema referenced only by SchemaDefinition triggers no-unused-components rule

### ISSUE THREAD

**Issue by michaelgwelch** [Redocly/redocly-cli#838]
**Describe the bug**

We use "server sent events" as part of our API. We document the schemas of these events in the components.schemas section of the OpenAPI spec. Then we use `<SchemaDefinition>` to reference those schemas (typically in a tag description). The schemas are then inlined in the description when the docs are rendered and an example (if part of the schema definition) is showed in the side panel.

However, when we build our docs the no-unused-components rule is triggered by these schemas. The rules says that it is triggered for any components not referenced by a $ref. So it makes sense that the rule is triggered.

It's not clear to me where <SchemaDefinition> is even documented but it is mentioned in this blog post: https://redocly.com/docs/api-reference-docs/specification-extensions/x-tags/

(Note: we'd prefer to use x-tags, but it doesn't appear to actually be implemented?)

**To Reproduce**
1. I started with open-api-starter project and ran bundle to get `bundled.yaml`
2. Then I edited bundled.yaml until it looked like the file down below. 
3. Lint it with `npx redocly lint bundled.yaml` and you'll see the rule triggered. 

```bash
npx redocly lint bundled.yaml
validating bundled.yaml...
[1] bundled.yaml:64:5 at #/components/schemas/person

Component: "person" is never used.

62 |           write:users: modify or remove users
63 | schemas:
64 |   person:
65 |     type: object
66 |     properties:

Error was generated by the no-unused-components rule.


bundled.yaml: validated in 49ms

❌ Validation failed with 1 error.
```

**Expected behavior**
Ideally a <SchemaDefinition> reference would be sufficient to consider the component used (else every use of it will cause a warning and make it difficult to determine when you have an actually unused component).

**OpenAPI definition**

Using 3.0.3 and will work on providing an example.

Here's a stripped down open-api-starter example which is actually 3.1.0. The person tag uses a SchemaDefinition to reference the `person` schema in the `components.schemas` section

```yaml
openapi: 3.1.0
info:
  version: 1.0.0
  title: Example.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  x-logo:
    url: https://redocly.github.io/openapi-template/logo.png
  description: >
    This is an **example** API to demonstrate potential enhancement to
    `no-unused-components` rule.

tags:
  - name: User
    description: |
      Operations about users.

      <SchemaDefinition schemaRef="#/components/schemas/person"/>
servers:
  - url: https://{tenant}/api/v1
    variables:
      tenant:
        default: www
        description: Your tenant id
  - url: https://example.com/api/v1
paths:
  /users:
    get:
      tags:
        - User
      summary: Get user by user name
      description: |
        Some description of the operation.
        You can use `Markdown` here.
      operationId: getUserByName
      security:
        - main_auth:
            - read:users
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
        '403':
          description: Forbidden
          content:
            application/json:
              example: Error

components:
  securitySchemes:
    main_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://example.com/api/oauth/dialog
          scopes:
            read:users: read users info
            write:users: modify or remove users
  schemas:
    person:
      type: object
      properties:
        name:
          type: string
        age:
          type: integer

```

**Redocly Version(s)**

1.0.0-beta.95

**`Node.js` Version(s)**

16.15.0

**Additional context**

**Comment by adamaltman** [comment]
@michaelgwelch `x-tags` is implemented, but are you using our premium product? (That's a feature in our premium product. We may be porting it to the community edition some day.)

I discuss a variety of options here: https://redocly.com/blog/display-schemas/

I don't think this is exactly a bug, because the schema definition tag is not a real usage per OAS.

https://redocly.com/docs/cli/rules/no-unused-components/ 

You can disable the rule, or add an ignore file (`--generate-ignore-file`). For reference:

- Disable the rule
    ```yaml
        rules:
           no-unused-components: off
    ```
- https://redocly.com/docs/cli/commands/lint/#generate-ignore-file

This rule doesn't make sense for a lot of organizations. In OAS 3.1, paths are optional. Some organizations define common schemas in a separate stand-alone OAS definition, and then reference it from other OAS definitions. That common file would flag on this rule too, but as I mentioned this rule doesn't make sense for every situation.

**Comment by michaelgwelch** [comment]
> You can disable the rule, or add an ignore file (--generate-ignore-file). For reference:

I got confused on how to disable the rule. I just set it to `off` but it didn't seem to do anything. I guess that's a separate `lint config` file for setting severity: https://redocly.com/docs/cli/commands/lint/#lint-config-file

Anyway, after using `--generate-ignore-file` I see that I can explicitly ignore specific instances of components by specifying their path. This is a more than adequate solution for us. Thank you.

You can close this and  https://github.com/Redocly/redoc/issues/2148

**Comment by tatomyr** [comment]
@michaelgwelch you can skip the rule explicitly: https://redocly.com/docs/cli/commands/lint/#skip-preprocessor-or-rule or switch it off using [Redocly config file](https://redocly.com/docs/cli/configuration/):

```yaml 
# redocly.yaml

styleguide:
   extends: [recommended]
   rules: 
      no-unused-components: off
      
```
