### ISSUE TITLE
Rename type: DefinitionRoot to Root 

### ISSUE THREAD

**Issue by adamaltman** [Redocly/redocly-cli#839]
**Is your feature request related to a problem? Please describe.**

Trying to make our type names more clear. I think `Root` is better than `DefinitionRoot`. It will also look better in diagrams.

**Describe the solution you'd like**

Rename `DefinitionRoot` to `Root`.

**Describe alternatives you've considered**

Doing nothing.

**Additional context**

I think the time to do it is now, prior to any GA release.

**Comment by tatomyr** [comment]
Do we want to update also other types to be more consistent? Like single VS plural forms in maps?

**Comment by adamaltman** [comment]
I think that would be a good idea. But we'll need to keep the old ones for backwards compatibility for now too.
