### ISSUE TITLE
operation-4xx-response rule indicates to use "4xx" (downcase), but OAS standard defines "4XX" (upcase)

### ISSUE THREAD

**Issue by ahx** [Redocly/redocly-cli#840]
**Describe the bug**
If I understand The OpenAPI Specification correctly, it [defines a "4XX"](https://spec.openapis.org/oas/latest.html#patterned-fields-0) (or 2XX …) response with uppercase "X". This is also reflected in the [OAS JSON Schema](https://github.com/OAI/OpenAPI-Specification/blob/main/schemas/v3.1/schema.yaml#L559). 

The error message from redocly lint is:

> Operation must have at least one `4xx` response.

**Expected behavior**
The error message should be:

> Operation must have at least one `4XX` response.

**OpenAPI definition**

**Redocly Version(s)**
1.0.0-beta.106

**`Node.js` Version(s)**
v18.5.0

**Comment by adamaltman** [comment]
Thanks for the PR @ahx (I hope we can release it soon).
