### ISSUE TITLE
Linter errors parameter when parameter is referenced in a response

### ISSUE THREAD

**Issue by benatdelta** [Redocly/redocly-cli#843]
**Describe the bug**

If a response references an object in /components/parameters/ the parameter object is shown as the error.

**To Reproduce**
1. Given this `redocly.yaml` file
```
# See https://redocly.com/docs/cli/configuration/

apis:
  # Update the apiName with your actual API name, and the version with your actual API version.
  apiName@version:
    # Update the path to your OpenAPI root file
    root: ./openapi.yaml
lint:
  extends:
    - recommended
  rules:
    no-path-trailing-slash: off

features.openapi:
  generateCodeSamples:
    languages:
      - lang: curl
      - lang: Node.js
      - lang: Python
```
2. And this OpenAPI file(s)
```
openapi: 3.1.0
info:
  title: Testing Schema
  version: v1
servers:
  - url: https://www.example.com
paths:
  /client/{id}:
    parameters:
      - $ref: "#/components/parameters/id"
    get:
      summary: an example of a get
      responses:
        $ref: "#/components/parameters/id"
                  
components:
  parameters:
    id:
      name: id
      required: true
      in: "path"
      description: Object ID (UUID)
      schema:
        $ref: "#/components/schemas/UUID"
        
  schemas:
    UUID:
      type: string
      format: uuidv4
```
3. Run this command with these arguments... `redocly ...`
`redocly lint swagger_testing.yml`
```
[1] swagger_testing.yml:19:7 at #/components/parameters/id/name

Property `name` is not expected here.

17 | parameters:
18 |   id:
19 |     name: id
20 |     required: true
21 |     in: "path"

Error was generated by the spec rule.
```
**Expected behavior**

The linter throws an error that a response schema cannot contain a reference to parameters in components

**Logs**

**OpenAPI definition**

**Redocly Version(s)**

1.0.0-beta.108
**`Node.js` Version(s)**

8.15.0
**Additional context**

Ill be honest I do not know if this an enhancement to the redocly linter or an issue with OAS 3.1.

**Comment by adamaltman** [comment]
There is an error in your OpenAPI:

```
      responses:
        $ref: "#/components/parameters/id"
```

I wish the error was more clear, but we did just make a change in https://github.com/Redocly/redocly-cli/pull/835 (not released yet) which would augment this error message to show where it is referenced from.

```
[1] swagger_testing.yml:19:7 at #/components/parameters/id/name

Property `name` is not expected here.

17 | parameters:
18 |   id:
19 |     name: id
20 |     required: true
21 |     in: "path"

Error was generated by the spec rule.
```

The problem is you're referencing a parameter but from the responses it would expect a responses map, not a parameter.

Here is an example of a functional one:

```
     responses:
        '200':
             description: OK
```

Although, IMO it is better to describe responses in more detail:

- https://redocly.com/docs/openapi-visual-reference/responses/
- https://redocly.com/docs/openapi-visual-reference/response/
- https://redocly.com/docs/openapi-visual-reference/media-type/

**Comment by benatdelta** [comment]
Hey @adamaltman

Fantastic to see a fix has been merged!
Yes I already know that my example OpenAPI has an error, that is the whole point of the issue. This is an error that I came across while fixing a 4000 line spec that I inherited from another department.

Thank you for the help!
