### ISSUE TITLE
lint command breaks when apis point to folder

### ISSUE THREAD

**Issue by AntonKozachuk** [Redocly/redocly-cli#844]
**Describe the bug**
When the user mistakenly points to the folder instead of the file, we show a confusing message:
`redocly lint folder-name/
`

<img width="1090" alt="image" src="https://user-images.githubusercontent.com/54616703/187913700-82f77cad-2ef1-48cb-9829-abb6a7d0a0a1.png">

**To Reproduce**
1. Use `redocly lint folder-name/`
4. See fuzzy error.

**Expected behavior**
Add more human-readable error message.

**Logs**
N/a

**OpenAPI definition**
N/a

**Redocly Version(s)**
Latest.

**`Node.js` Version(s)**
N/a

**Additional context**
N/a

**Comment by jeremyfiel** [comment]
> Expected behavior
> Add more human-readable error message.

or add the ability to pass a folder as the target.  In our case, we would like to use the folder location as the input for our build process.  the current workaround is using a glob pattern based on our file naming conventions. 

`redocly lint --config ~/.redocly.yaml /specs/**/**/**/*openapi*`

I'm not super confident in this approach for future maintenance

**Comment by lornajane** [comment]
Let's stick with a better error message for now, there are a lot of possible interpretations of the feature to support folders and we should develop the feature request on that separately.

@jeremyfiel I think your command implies that you lint a whole directory of OpenAPI files - but without configuring which files those should be in your configuration, is that right. Would using the config file to specify the API files be a viable workaround for you?

**Comment by jeremyfiel** [comment]
Yes, we build our docs and a few other jobs run against the entire API registry we have. Can you share some ways you've seen others add the necessary apis to config?  Are they doing it at runtime or manually? 

We only use config for linting and I'm not targeting any specific apis. The glob we use filters any other files in the directory

**Comment by lornajane** [comment]
I know we merged a change for this but to answer @jeremyfiel : Manually (as in, probably ten minutes with a bash script) add APIs to a config file, something like:

```
apis:
  users@v1:
    root: apis/users.yaml
  products@v1:
    root: apis/products.yaml
  orders@v1:
    root: apis/orders.yaml
```

The `lint` command will just pick all the files out of the config and lint them all. It also means you can refer to them by their short name if you're just linting one repeatedly while you fix something. Hope that helps!
