### ISSUE TITLE
lint command isn't working with URLs from API Registry used inline

### ISSUE THREAD

**Issue by AntonKozachuk** [Redocly/redocly-cli#850]
**Describe the bug**
When you try to use the `lint` command and define API inline as a URL from API Registry, which has a branch query string, the command seems to break.
At the same time, it works when used inside the `apis` section of the configuration file. 

Example:
`redocly lint "https://api.redocly.com/registry/bundle/example/v1/latest/openapi.yaml?branch=release"
`
The `?branch=release` part seems to break the command.

**To Reproduce**
1. Add a definition to the API Registry or open an existing one.
2. Copy the link to the definition's [snapshot](https://redocly.com/docs/api-registry/guides/snapshots/#how-to-find-your-snapshot-links).
3. Try to use it with the lint command.
4. See error.

**Expected behavior**
The lint command works as expected when used with URLs from the API Registry.

**Logs**
N/a

**OpenAPI definition**
N/a

**Redocly Version(s)**
latest

**`Node.js` Version(s)**
15

**Additional context**
Some context can be found here: [redoc-ly.slack.com/archives/C02UHE7EL3E/p1661807377826659](https://redoc-ly.slack.com/archives/C02UHE7EL3E/p1661807377826659)

**Comment by lornajane** [comment]
I'm not sure when this old issue was fixed, but retesting it today I cannot replicate the issue (and I'm sure I've used this before without a problem)
