### ISSUE TITLE
document or delete info-description rule

### ISSUE THREAD

**Issue by adamaltman** [Redocly/redocly-cli#854]
We should document or delete the info-description rule. It feels a bit unnecessary given `assertions` capability to do that equivalent really easily.

**Comment by tatomyr** [comment]
I'd vote for deletion.

**Comment by adamaltman** [comment]
Let's do it then.

**Comment by jeremyfiel** [comment]
any reason the vote was against an `info-description` rule? 
the PR states `it's easy to make an assertion`

Are you planning to remove any rule that can be an assertion in the future? Are you documenting and sharing any list of assertions currently available?

**Comment by tatomyr** [comment]
> Are you planning to remove any rule that can be an assertion in the future? 

@jeremyfiel No we don't :) 

> Are you documenting and sharing any list of assertions currently available?

We are still working on changes to the assertions syntax. We do plan to remove the `undefined` assertion (since it duplicates the `defined` one).  You can check the current state in the draft here: https://github.com/Redocly/redocly-cli/pull/917
