### ISSUE TITLE
Include an assert function name into assertion messages

### ISSUE THREAD

**Issue by tatomyr** [Redocly/redocly-cli#855]
**Is your feature request related to a problem? Please describe.**

If more than one assert functions are defined, it is not clear which one triggered the assertion failure. If both of the functions fail, the output contains two identical messages.

**Describe the solution you'd like**

Including an assert function name  into the output (like `patern`, `casing` or a custom name) would be handy to identify the cause of the failure.

**Describe alternatives you've considered**

Collapsing all the assertion messages into one. But it would require more efforts and also would be less clear to a user.

**Additional context**

[Internal discussion](https://redoc-ly.slack.com/archives/C02UHE7EL3E/p1662061195536239)

**Comment by adamaltman** [comment]
@RomanHotsiy and I discussed the required placeholders for assertion messages last night. @RomanHotsiy did you want to add it to this ticket?

**Comment by RomanHotsiy** [comment]
Details here: https://github.com/Redocly/redocly-cli/pull/857/files#diff-278dfad5d57e4b60a03f414c74a1d4c5d5273dd755ffae1b201c8338e36fd824R37

**Comment by adamaltman** [comment]
I copied it here in case that linked PR changes: 

> Problem message displayed if the assertion is false. If omitted, the default message is: "{{assertionName}} failed because the {{subject}} {{property}} didn't meet the assertions: {{problems}}" is displayed. The available placeholders are displayed in that message. In the case there are multiple properties, the `{{property}}` placeholder produces a comma and space separate list of properties. In case there are multiple problems, the `{{problems}}` placeholder produces a bullet-list with a new line between each problem.
