### ISSUE TITLE
config option: remove version from API title

### ISSUE THREAD

**Issue by ArtFlag** [Redocly/redocly-cli#858]
**Is your feature request related to a problem? Please describe.**

When I preview my docs, the API version is appended to the API title as an H1 title by default.

**Describe the solution you'd like**

I would like to be able to not insert the version in the title.

**Comment by tatomyr** [comment]
@ArtFlag, do you mean you're using `preview-docs` command? Could you put a screenshot here?

**Comment by adamaltman** [comment]
@ArtFlag the version won't display if you change your version to an empty string, for example.

https://redocly.com/docs/openapi-visual-reference/info/#version-examples

You can set the version as an empty string pro grammatically by using a decorator.

I'd recommend looking at these: https://redocly.com/docs/cli/decorators/ to get a sense of how to create one. We don't have a step-by-step guide for that yet.

**Comment by ArtFlag** [comment]
@tatomyr that's right, I generate the output with `preview-docs`. 

@adamaltman setting the version to an empty string did the trick thanks a lot 😊
