### ISSUE TITLE
remove-unused-components rule is not processed transitively

### ISSUE THREAD

**Issue by cliffred** [Redocly/redocly-cli#874]
**Describe the bug**
Given the following snippet:
```yaml
Customer:
  type: object
  properties:
    id:
      type: string
    username:
      type: string
    address:
      $ref: '#/components/schemas/Address'
```

Assume that Customer is unused and Customer is the only component with a reference to Address. On linting only Customer is shown as an unused component. But once that one is removed Address becomes unused. 

The same goes for `redocly bundle input.yaml --remove-unused-components -o output.yaml`. You need multiple passes to remove all unused components.

I think it would make sense to process this rule recursively to not need multiple passes to remove all unused components.

**To Reproduce**
`redocly lint https://petstore3.swagger.io/api/v3/openapi.json`
It shows among others _Component: "Customer" is never used._
Which after removal will result in Address never being used.

**Expected behavior**
Show all components are not referenced, whether it's directly or indirectly.

**Redocly Version(s)**
1.0.0-beta.109

**Comment by RomanHotsiy** [comment]
Yes, I believe we mark `Address` as used when we traverse `components`.
An easy fix may be to disable marking usage from `components` 🤔 .

**Comment by adamaltman** [comment]
Also a remove-unused-components issue here: #944

**Comment by jazanne** [comment]
this is pretty frustrating... i had to write a script that keeps rerunning command until all unused components are actually removed

**Comment by tatomyr** [comment]
Tangentially related: https://github.com/Redocly/redocly-cli/issues/1209
