### ISSUE TITLE
Publish docker container to GitHub Packages

### ISSUE THREAD

**Issue by AlexVarchuk** [Redocly/redocly-cli#875]
Publish `@redocly/cli` docker container to [GitHub Packages](https://docs.github.com/en/packages)(add action for it).

Also, the current docker container is not renamed in [dockerHub](https://hub.docker.com/r/redocly/openapi-cli).
It can be confusing for some users.

**Comment by lornajane** [comment]
Let's get this tidied up and stop publishing old package names in the major release.
