### ISSUE TITLE
the 'lint' field is deprecated.

### ISSUE THREAD

**Issue by Zacama** [Redocly/redocly-cli#909]
Hello, I get a deprecation warning when I execute ‘redocly lint  openapi.yaml’.
![image](https://user-images.githubusercontent.com/50320281/195008231-12fb4bad-f688-42cd-986f-e5d2f4fe85fa.png)
it tells me to go to this url to read the details. But I didn't find anything about lint deprecation at that url.
![image](https://user-images.githubusercontent.com/50320281/195008670-9fb2a0d5-26c2-4edb-b23b-fbe13517b47a.png)
And the 'New Configuration' example even use 'lint' field.

**Comment by Zacama** [comment]
Ok, thank you very much. I'm going to read that page.

**Comment by adamaltman** [comment]
I also updated this page:

https://redocly.com/docs/api-registry/guides/migration-guide-config-file/
