### ISSUE TITLE
Implement `no unused tags` built-in rule

### ISSUE THREAD

**Issue by tatomyr** [Redocly/redocly-cli#953]
**Is your feature request related to a problem? Please describe.**
We should be able to detect tags that are not in use.

**Describe alternatives you've considered**

Doing nothing 

**Additional context**

 https://redoc-ly.slack.com/archives/C02UHE7EL3E/p1669055525800369

**Comment by lornajane** [comment]
From the internal slack discussion, some extra context in case anyone is following along with the public project:

* This is based on a custom rule that is used on Rebilly's API and it's great so probably we should share it :heart: 
* Identify tags used in paths but not declared at the top level of the spec
* Identify tags declared at the top level of the spec but not actually used anywhere
* Add an `ignoredTags` array to the configuration in case there are any tags that should be left alone for another reason.

**Comment by lornajane** [comment]
This rule is available as a custom plugin from our cookbook: https://github.com/Redocly/redocly-cli-cookbook/tree/main/custom-plugin-decorators/remove-unused-tags
