### ISSUE TITLE
Add an option to exclude webhooks from operation-4xx-response rule

### ISSUE THREAD

**Issue by AntonKozachuk** [Redocly/redocly-cli#955]
**Is your feature request related to a problem? Please describe.**
In terms of our [operation-4xx-response/](https://redocly.com/docs/cli/rules/operation-4xx-response/) rule we treat webhooks the same as path items (as it's intended by the spec). 
However, webhooks ofter times are treated differently than path items so it makes sense to provide an option to exclude them from the rule. 

**Describe the solution you'd like**
Add an option to exclude webhooks from the operation-4xx-response rule and similar ones.

**Describe alternatives you've considered**
Avoid applying the rule to the webhooks at all.

**Additional context**
https://redoc-ly.slack.com/archives/C02UHE7EL3E/p1669127864676219

**Comment by AntonKozachuk** [comment]
@adamaltman should this be applied to `operation-4xx-response` rule too?

**Comment by adamaltman** [comment]
Yes, I think it should. (Even though in this particular example case there are 2xx responses defined.)
