### ISSUE TITLE
support bundle --output <path> for single api as well

### ISSUE THREAD

**Issue by fellnerse** [Redocly/redocly-cli#977]
**Is your feature request related to a problem? Please describe.**
I would like to be able to specify the output folder for a single api for the bundle command:

`redocly bundle --output ./public/`

But at the moment this would generate a `public.yaml` file at the root.

**Describe the solution you'd like**
`redocly bundle --output ./public/` should should put the generated file inside the folder instead of naming the file like the folder.

**Describe alternatives you've considered**
 It might make sense to have an option in the redocly config file to specify the output path generally and then also individually for each api.

**Comment by tatomyr** [comment]
Hi @fellnerse,

It could be a bug.

**Comment by meganhng** [comment]
Hey, I was wondering the progress on this issue I'm encountering the same problem. I noticed that there was a update fixing the issue when you provide an array of `apis` values, but in the scenario where the `apis` argument is not provided but there are multiple files being picked up it is still generating a file from the output instead of a folder.

**Comment by tatomyr** [comment]
Hi @meganhng, actually, the docs are explicit about the behaviour: [single file](https://redocly.com/docs/cli/commands/bundle#bundle-a-single-api-description) VS [multiple files](https://redocly.com/docs/cli/commands/bundle#bundle-multiple-api-descriptions), so I'm closing the issue.

You can either specify the exact file inside a folder (e.g. `redocly bundle openapi.yaml --output dist/openapi.yaml`) or use the new `output` property in the `apis` section of the **redocly.yaml** config (see [the docs](https://redocly.com/docs/cli/configuration/reference/apis#api-object)).

Please let me know if you think I'm missing something.
