### ISSUE TITLE
@redocly/cli@1.0.0-beta.118: OASDecorator: context.resolve() cannot resolve external oas attributes if refs exist in array

### ISSUE THREAD

**Issue by afmhenry** [Redocly/redocly-cli#992]
**The bug**

Introduction of SpecExtension has caused redocly plugin decorator context.resolve() to fail, when applied to nodes belonging to an external oas attributes (x-) containing an array. 

Can be reproduced since upgrading to @redocly/cli@1.0.0-beta.118
Can likewise be "resolved" by downgrading to @redocly/cli@1.0.0-beta.117

**To Reproduce**

1. unzip attached folder
2. `npm i @redocly/cli@1.0.0-beta.118`
3. `npx redocly bundle --config config.yaml oas-spec.yaml --output oas-spec-bundled.yaml`
4. Observed console output: the "x-bug" is not resolved, but "no-bug" is
```
x-bug node undefined
no-bug node { test: 'this', test1: 'succeeds on all versions' }
```
5. `npm i @redocly/cli@1.0.0-beta.117`
6. `npx redocly bundle --config config.yaml oas-spec.yaml --output oas-spec-bundled.yaml`
7. Both references are resolved in the console logs
```
x-bug node { test: 'this', test1: 'fails on versions .118+' }
no-bug node { test: 'this', test1: 'succeeds on all versions' }
```

**Expected behavior**
Can resolve field if it starts with "x-", even contained in an array entry. 

**Observed**
Cannot resolve ref in array, if it belongs to a key that starts with "x-"
Can resolve $ref in array if it doesn't belong to a key that starts with "x-"

**Full Code Scenario**
[redocly.zip](https://github.com/Redocly/redocly-cli/files/10444257/redocly.zip)

**Redocly Version(s)**
@redocly/cli@1.0.0-beta.117
@redocly/cli@1.0.0-beta.118

**Comment by adamaltman** [comment]
Have you tried with with `1.0.0-beta.120`? There were some fixes related to specification extension type in that:

https://redocly.com/docs/cli/changelog/#100-beta120-2023-01-05

> Fixed an issue where `$refs` weren't resolved inside specification extensions.

**Comment by afmhenry** [comment]
I have, 1.0.0-beta.118  and above all fail with the above given scenario

**Comment by adamaltman** [comment]
Yes, this was fixed in `1.0.0-beta.120`.

**Comment by afmhenry** [comment]
Hi @adamaltman I hope I'm not very very wrong, but have you tried the scenario I provided? fresh installs (local and global) to the @redocly/cli@1.0.0-beta.120 version still result in my scenario failing. 

![image](https://user-images.githubusercontent.com/10469240/214611337-efd7d580-4961-4f0c-a4a0-5bee6e2cd1c6.png)

Appreciate you looking into this! If I was savvy enough to investigate myself, I would try :)

**Comment by adamaltman** [comment]
I can reproduce it @afmhenry even on `1.0.0-beta.122` and it seems tied into the array usage as you said above. Thank you. 

When it is not an array, it succeeds in resolving the reference. Also, when the reference appears anywhere else once it was previously resolved, then it is resolved correctly (reference resolutions are cached).

For example, changing the OpenAPI file like this will result in it being resolved:
```yaml
  x-nobug:
    $ref: external.yaml#/Test1
  x-bug:
    - $ref: external.yaml#/Test1
```

**Comment by afmhenry** [comment]
This is consistent with what I experienced--even experienced the caching, when I was setting up my test scenario. What an edge case!

For my purposes I'll just stick on 117 until there's a fix available. 

Thanks for looking into this :)
