### ISSUE TITLE
Question: local $ref in external file

### ISSUE THREAD

**Issue by antusus** [Redocly/redocly-cli#996]
Hello,
I'm trying to split my YML files into smaller parts so that it will be easier to work with. I have main file `api-paths-extracted.yml`
```yml
openapi: 3.0.2
info:
  description: |-
    This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about
    Swagger at [http://swagger.io](http://swagger.io).
  version: 1.0.17
  title: Swagger Petstore - OpenAPI 3.0
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: pet
    description: Everything about your Pets
paths:
  /pet:
    put:
      $ref: './pet_put.yml'
components:
  schemas:
    $ref: './components.yml'
```
In `components.yml` I have `Pet` definition and in `pet_put.yml` I would love to reference it using `#/components/schemas/Pet`. However if I run `lint` or `bundle` it will complain that in `pet_put.yml` reference to `#/components/schemas/Pet` is unknown. Is there a way to handle that in `redocly-cli`.
I'm using `redocly-cli` in version `1.0.0-beta.120`.
My command:
```bash
node node_modules/@redocly/cli/bin/cli.js bundle ./schemas/pet/api-paths-extracted.yml  --output api-bundled.yml
```
Files that I'm using
[Archive.zip](https://github.com/Redocly/redocly-cli/files/10489377/Archive.zip)

**Comment by adamaltman** [comment]
No, you should reference it like `$ref: ./path-to-file.yml`. The reference will change once you bundle the file and inspect the output.

One of the easiest ways to see this is to use the split command:

```
npx @redocly/cli split openapi.yaml --outDir split
```
Inspect the files.

Then bundle the split file
```
npx @redocly/cli bundle split/openapi.yaml -o dist/bundled.yaml
```
Then inspect bundled.yaml and you will see the references are local. The reference parts roughly mean `#` in this file, `/` from the root of the file, `components` to the components property, `schemas` to the schemas property, `Pet`, to the Pet property.

**Comment by lornajane** [comment]
This looks like a good answer so I'll close the issue - but let us know if you need anything else on this, @antusus ?
